package com.sedsoftware.exchange.binance.entity

import com.sedsoftware.core.domain.entity.Currency

@Suppress("LargeClass")
enum class BinanceCurrency(override val label: String) : Currency {
    ADA("Cardano"),
    ADX("AdEx"),
    AE("Aeternity"),
    AGI("SingularityNET"),
    AION("Aion"),
    AMB("Ambrosus"),
    APPC("AppCoins"),
    ARDR("Ardor"),
    ARK("Ark"),
    ARN("Aeron"),
    AST("AirSwap"),
    BAT("Basic Attention Token"),
    BCC("Bitcoin Cash"),
    BCD("Bitcoin Diamond"),
    BCHABC("Bitcoin Cash ABC"),
    BCHSV("Bitcoin Cash SV"),
    BCN("Bytecoin"),
    BCPT("BlockMason Credit Protocol"),
    BLZ("Bluzelle"),
    BNB("Binance Coin"),
    BNT("Bancor"),
    BQX("Ethos"),
    BRD("Bread"),
    BTC("Bitcoin"),
    BTG("Bitcoin Gold"),
    BTS("BitShares"),
    BTT("BitTorent"),
    CDT("Blox"),
    CHAT("ChatCoin"),
    CLOAK("CloakCoin"),
    CMT("CyberMiles"),
    CND("Cindicator"),
    CVC("Civic"),
    DASH("Dash"),
    DATA("Streamr DATAcoin"),
    DCR("Decred"),
    DENT("DENT"),
    DGD("DigixDAO"),
    DLT("Agrello Delta"),
    DNT("district0x"),
    DOCK("Dock"),
    EDO("Eidoo"),
    ELF("aelf"),
    ENG("Enigma"),
    ENJ("Enjin Coin"),
    EOS("EOS"),
    ETC("Ethereum Classic"),
    ETH("Ethereum"),
    EVX("Everex"),
    FET("Fetch.AI"),
    FUEL("Etherparty"),
    FUN("FunFair"),
    GAS("NeoGas"),
    GNT("Golem"),
    GO("GoChain"),
    GRS("Groestlcoin "),
    GTO("Gifto"),
    GVT("Genesis Vision"),
    GXS("GXChain"),
    HC("HyperCash"),
    HOT("Holo"),
    HSR("Hshare"),
    ICN("Iconomi"),
    ICX("ICON"),
    INS("INS Ecosystem"),
    IOST("IOStoken"),
    IOTA("MIOTA"),
    IOTX("IoTeX"),
    KEY("Selfkey"),
    KMD("Komodo"),
    KNC("KyberNetwork"),
    LEND("EthLend"),
    LINK("ChainLink"),
    LOOM("Loom Network"),
    LRC("Loopring"),
    LSK("Lisk"),
    LTC("Litecoin"),
    LUN("Lunyr"),
    MANA("Decentraland"),
    MCO("Monaco"),
    MDA("Moeda Loyalty Points"),
    MFT("Mainframe"),
    MITH("Mithril"),
    MOD("Modum"),
    MTH("Monetha"),
    MTL("Metal"),
    NANO("Nano"),
    NAS("Nebulas"),
    NAV("NAV Coin"),
    NCASH("Nucleus Vision"),
    NEBL("Neblio"),
    NEO("NEO"),
    NPXS("Pundi X"),
    NULS("Nuls"),
    NXS("Nexus"),
    OAX("OpenANX"),
    OMG("OmiseGO"),
    ONG("Ontology Gas"),
    ONT("Ontology"),
    OST("OST"),
    PAX("Paxos Standard"),
    PHX("Phoenix"),
    PIVX("Private Instant Verified Transaction"),
    POA("POA Network"),
    POE("Po.et"),
    POLY("Polymath Network"),
    POWR("PowerLedger"),
    PPT("Populous"),
    REN("Ren"),
    QKC("QuarkChain"),
    QLC("QLC Chain"),
    QSP("Quantstamp"),
    QTUM("Qtum"),
    RCN("Ripio Credit Network"),
    RDN("Raiden Network Token"),
    REP("Augur"),
    REQ("Request Network"),
    RLC("iEx.ec RLC"),
    RPX("Red Pulse"),
    RVN("Ravencoin"),
    SALT("Salt"),
    SC("Siacoin"),
    SKY("Skycoin"),
    SNGLS("SingularDTV"),
    SNM("SONM"),
    SNT("Status Network Token"),
    STEEM("Steem"),
    STORJ("Storj"),
    STORM("Storm"),
    STRAT("Stratis"),
    SUB("Substratum"),
    SYS("SysCoin"),
    THETA("Theta Token"),
    TNB("Time New Bank"),
    TNT("Tierion"),
    TRIG("Triggers"),
    TRX("TRON"),
    TUSD("TrueUSD"),
    USDC("USD Coin"),
    USDS("Stable USD"),
    USDT("Tether"),
    VEN("Vechain"),
    VET("VeChainThor"),
    VIA("Viacoin"),
    VIB("Viberate"),
    VIBE("VIBEHub"),
    WABI("WaBi"),
    WAN("Wancoon"),
    WAVES("Waves"),
    WINGS("WINGS"),
    WPR("WePower"),
    WTC("Walton"),
    XEM("NEM"),
    XLM("Stellar"),
    XMR("Monero"),
    XRP("Ripple"),
    XVG("Verge"),
    XZC("ZCoin"),
    YOYO("Yoyow"),
    ZEC("ZCash"),
    ZEN("ZenCash"),
    ZIL("Zilliqa"),
    ZRX("0x"),
}
