package com.sedsoftware.exchange.binance.entity

import com.sedsoftware.core.domain.entity.Currency

@Suppress("LargeClass")
enum class BinanceCurrency(override val label: String) : Currency {
    ADA("Cardano"),
    ADX("AdEx"),
    AE("Aeternity"),
    AGI("SingularityNET"),
    AION("Aion"),
    ALGO("Algorand"),
    AMB("Ambrosus"),
    ANKR("Ankr Network"),
    APPC("AppCoins"),
    ARDR("Ardor"),
    ARK("Ark"),
    ARN("Aeron"),
    AST("AirSwap"),
    ATOM("Cosmos"),
    BAT("Basic Attention Token"),
    BCC("Bitcoin Cash"),
    BCD("Bitcoin Diamond"),
    BCHABC("Bitcoin Cash ABC"),
    BCHSV("Bitcoin Cash SV"),
    BCN("Bytecoin"),
    BCPT("BlockMason Credit Protocol"),
    BGBP("BGBP"),
    BLZ("Bluzelle"),
    BNB("Binance Coin"),
    BNT("Bancor"),
    BQX("Ethos"),
    BRD("Bread"),
    BTC("Bitcoin"),
    BTCB("Bitcoin BEP2"),
    BTG("Bitcoin Gold"),
    BTS("BitShares"),
    BTT("BitTorent"),
    CDT("Blox"),
    CELR("Celer Network"),
    CHAT("ChatCoin"),
    CLOAK("CloakCoin"),
    CHZ("Chiliz"),
    CMT("CyberMiles"),
    CND("Cindicator"),
    COCOS("COCOS-BCX"),
    COS("Contentos"),
    CVC("Civic"),
    DASH("Dash"),
    DATA("Streamr DATAcoin"),
    DCR("Decred"),
    DENT("DENT"),
    DGD("DigixDAO"),
    DLT("Agrello Delta"),
    DNT("district0x"),
    DOCK("Dock"),
    DOGE("Dogecoin"),
    DUSK("Dusk Network"),
    EDO("Eidoo"),
    ELF("aelf"),
    ENG("Enigma"),
    ENJ("Enjin Coin"),
    EOS("EOS"),
    ERD("Elrond"),
    ETC("Ethereum Classic"),
    ETH("Ethereum"),
    EVX("Everex"),
    FET("Fetch.AI"),
    FTM("Fantom"),
    FUEL("Etherparty"),
    FUN("FunFair"),
    GAS("NeoGas"),
    GNT("Golem"),
    GO("GoChain"),
    GRS("Groestlcoin "),
    GTO("Gifto"),
    GVT("Genesis Vision"),
    GXS("GXChain"),
    HC("HyperCash"),
    HOT("Holo"),
    HSR("Hshare"),
    ICN("Iconomi"),
    ICX("ICON"),
    INS("INS Ecosystem"),
    IOST("IOStoken"),
    IOTA("MIOTA"),
    IOTX("IoTeX"),
    KEY("Selfkey"),
    KMD("Komodo"),
    KNC("KyberNetwork"),
    LEND("EthLend"),
    LINK("ChainLink"),
    LOOM("Loom Network"),
    LRC("Loopring"),
    LSK("Lisk"),
    LTC("Litecoin"),
    LUN("Lunyr"),
    MANA("Decentraland"),
    MATIC("MATIC Network"),
    MCO("Monaco"),
    MDA("Moeda Loyalty Points"),
    MFT("Mainframe"),
    MITH("Mithril"),
    MOD("Modum"),
    MTH("Monetha"),
    MTL("Metal"),
    NANO("Nano"),
    NAS("Nebulas"),
    NAV("NAV Coin"),
    NCASH("Nucleus Vision"),
    NEBL("Neblio"),
    NEO("NEO"),
    NPXS("Pundi X"),
    NULS("Nuls"),
    NXS("Nexus"),
    OAX("OpenANX"),
    OMG("OmiseGO"),
    ONE("Harmony"),
    ONG("Ontology Gas"),
    ONT("Ontology"),
    OST("OST"),
    PAX("Paxos Standard"),
    PERL("Perlin"),
    PHB("Red Pulse Phoenix Binance"),
    PHX("Phoenix"),
    PIVX("Private Instant Verified Transaction"),
    POA("POA Network"),
    POE("Po.et"),
    POLY("Polymath Network"),
    POWR("PowerLedger"),
    PPT("Populous"),
    REN("Ren"),
    QKC("QuarkChain"),
    QLC("QLC Chain"),
    QSP("Quantstamp"),
    QTUM("Qtum"),
    RCN("Ripio Credit Network"),
    RDN("Raiden Network Token"),
    REP("Augur"),
    REQ("Request Network"),
    RLC("iEx.ec RLC"),
    RPX("Red Pulse"),
    RVN("Ravencoin"),
    SALT("Salt"),
    SC("Siacoin"),
    SKY("Skycoin"),
    SNGLS("SingularDTV"),
    SNM("SONM"),
    SNT("Status Network Token"),
    STEEM("Steem"),
    STORJ("Storj"),
    STORM("Storm"),
    STRAT("Stratis"),
    SUB("Substratum"),
    SYS("SysCoin"),
    TFUEL("Theta Fuel"),
    THETA("Theta Token"),
    TNB("Time New Bank"),
    TNT("Tierion"),
    TOMO("TomoChain"),
    TRIG("Triggers"),
    TRX("TRON"),
    TUSD("TrueUSD"),
    TUSDB("TrueUSD BEP2"),
    USDC("USD Coin"),
    USDS("Stable USD"),
    USDSB("Stable USD BEP2"),
    USDT("Tether"),
    VEN("Vechain"),
    VET("VeChainThor"),
    VIA("Viacoin"),
    VIB("Viberate"),
    VIBE("VIBEHub"),
    WABI("WaBi"),
    WAN("Wancoon"),
    WAVES("Waves"),
    WINGS("WINGS"),
    WIN("WINK"),
    WPR("WePower"),
    WTC("Walton"),
    XEM("NEM"),
    XLM("Stellar"),
    XMR("Monero"),
    XRP("Ripple"),
    XVG("Verge"),
    XZC("ZCoin"),
    YOYO("Yoyow"),
    ZEC("ZCash"),
    ZEN("ZenCash"),
    ZIL("Zilliqa"),
    ZRX("0x"),
}
