package com.sedsoftware.core.common.enum

enum class Currency(val value: String) {
    ABC("AB-Chain"),
    ABJ("Abjcoin"),
    ABS("Absolute Coin"),
    ABT("ArcBlock"),
    ABY("ArtByte"),
    ABYSS("The Abyss"),
    AC("Asia Coin"),
    AC3("AC3"),
    ACAT("Alphacat"),
    ACC("AdCoin"),
    ACCO("Accolade"),
    ACE("TokenStars"),
    ACES("AcesCoin"),
    ACH("AchieveCoin"),
    ACID("AcidCoin"),
    ACN("AvonCoin"),
    ACOIN("ACoin"),
    ACP("Anarchists Prime"),
    ACT("Achain"),
    ACTN("Action Coin"),
    ADA("Cardano"),
    ADB("Adbank"),
    ADC("AudioCoin"),
    ADCN("Asiadigicoin"),
    ADH("Adhive"),
    ADK("Aidos Kuneen"),
    ADL("Adelphoi"),
    ADM("Adamant"),
    ADN("Aiden"),
    ADST("Adshares"),
    ADT("AdToken"),
    ADX("AdEx"),
    ADZ("Adzcoin"),
    AE("Aeternity"),
    AEC("AcesCoin"),
    AEON("AEON"),
    AERM("Aerium"),
    AERO("Aero Coin"),
    AET("AfterEther"),
    AGI("SingularityNET"),
    AGRS("Agoras Token"),
    AGS("Aegis"),
    AHT("Bowhead Health"),
    AIB("AdvancedInternetBlock"),
    AIC("AI Crypto"),
    AID("AidCoin"),
    AIDOC("AI Doctor"),
    AIMS("HighCastle Token"),
    AION("Aion"),
    AIR("Aircoin"),
    AIT("AIChain Token"),
    AITT("AITrading"),
    AIX("Aigang"),
    AKA("Akroma"),
    ALC("Arab League Coin"),
    ALEX("Alexandrite"),
    ALF("AlphaCoin"),
    ALG("Algory"),
    ALIS("ALISmedia"),
    ALN("AlienCoin"),
    ALPS("Alpenschillling"),
    ALQO("Alqo"),
    ALT("ALTcoin"),
    ALTCOM("AltCommunity Coin"),
    ALTOCAR("AltoCar"),
    ALX("ALAX"),
    AM("AeroMe"),
    AMB("Ambrosus"),
    AMBER("AmberCoin"),
    AMBT("AMBT Token"),
    AMC("AmericanCoin"),
    AMIS("AMIS"),
    AMM("MicroMoney"),
    AMMO("Ammo Rewards"),
    AMN("Amon"),
    AMO("Amo Coin"),
    AMP("Synereo"),
    AMS("Amsterdam Coin"),
    AMT("Acumen"),
    AMX("Amero"),
    AMY("Amygws"),
    ANAL("AnalCoin"),
    ANC("Anoncoin"),
    ANCP("Anacrypt"),
    AND("AndromedaCoin"),
    ANGL("Angel Token"),
    ANI("Animecoin"),
    ANK("Ankorus Token"),
    ANT("Aragon"),
    ANTC("AntiLitecoin"),
    ANTI("Anti Bitcoin"),
    ANTS("ANTS Reloaded"),
    AOA("Aurora "),
    AOP("Averopay"),
    APC("AlpaCoin"),
    APEX("ApexCoin"),
    APH("Aphelion"),
    APIS("APIS"),
    APPC("AppCoins"),
    APT("Aptcoin"),
    APX("Apx"),
    AR("Ar.cash"),
    ARB("Arbit Coin"),
    ARBI("Arbi"),
    ARC("ArcticCoin"),
    ARCH("ArchCoin"),
    ARCO("AquariusCoin"),
    ARCT("ArbitrageCT"),
    ARDR("Ardor"),
    ARE("ARENON"),
    ARENA("Arena"),
    ARG("Argentum"),
    ARGUS("ArgusCoin"),
    ARI("AriCoin"),
    ARK("ARK"),
    ARM("Armory Coin"),
    ARN("Aeron"),
    ARNA("ARNA Panacea"),
    ARO("Arionum"),
    ARPA("ArpaCoin"),
    ART("Maecenas"),
    ARTE("Artemine"),
    ARY("Block Array"),
    ASAFE2("Allsafe"),
    ASN("Ascension Coin"),
    AST("AirSwap"),
    ASTRO("Astronaut"),
    ATB("ATB coin"),
    ATCC("ATC Coin"),
    ATFS("ATFS Project"),
    ATH("Atheios"),
    ATKN("A-Token"),
    ATL("ATLANT"),
    ATM("Atonomi"),
    ATMI("Atonomi"),
    ATMOS("Atmos"),
    ATOM("Atomic Coin"),
    ATS("Authorship"),
    ATX("ArtexCoin"),
    AUA("ArubaCoin"),
    AUC("Auctus"),
    AUN("Authoreon"),
    AUR("Aurora Coin"),
    AURA("Aurora"),
    AURS("Aureus"),
    AUT("Autoria"),
    AUTO("Cube"),
    AV("Avatar Coin"),
    AVA("Avalon"),
    AVE("Avesta"),
    AVH("Animation Vision Cash"),
    AVL("Avalanche"),
    AVT("AventCoin"),
    AXIOM("Axiom Coin"),
    AXP("aXpire"),
    AXR("AXRON"),
    AXS("AXS"),
    AXT("AIX"),
    AXYS("Axys"),
    AZART("Azart"),
    B2B("B2BX"),
    B2X("SegWit2x"),
    B3("B3 Coin"),
    BAC("BitalphaCoin"),
    BAM("BAM"),
    BAN("Babes and Nerds"),
    BANCA("BANCA"),
    BAR("TBIS token"),
    BAS("BitAsean"),
    BASH("LuckChain"),
    BASHC("BashCoin"),
    BAT("Basic Attention Token"),
    BAX("BABB"),
    BAY("BitBay"),
    BBC("TraDove"),
    BBCC("BaseballCardCoin"),
    BBI("BelugaPay"),
    BBK("BitBlocks"),
    BBN("Banyan Network"),
    BBO("Bigbom"),
    BBP("BiblePay"),
    BBR("Boolberry"),
    BBT("BitBoost"),
    BCA("Bitcoin Atom"),
    BCAP("Blockchain Capital"),
    BCCOIN("BitConnect Coin"),
    BCD("Bitcoin Diamond"),
    BCDN("BlockCDN "),
    BCF("BitcoinFast"),
    BCH("Bitcoin Cash"),
    BCI("Bitcoin Interest"),
    BCIO("Blockchain.io"),
    BCN("ByteCoin"),
    BCO("BridgeCoin"),
    BCOIN("BannerCoin"),
    BCPT("BlockMason Credit Protocol"),
    BCR("Bitcoin Royal"),
    BCT("Blockchain Terminal"),
    BCX("BattleCoin"),
    BCY("BitCrystals"),
    BDG("BitDegree"),
    BDL("Bitdeal"),
    BDP("Bidipass"),
    BDR("BlueDragon"),
    BEE("Bee Token"),
    BELA("BelaCoin"),
    BEN("Benjamins"),
    BENJI("BenjiRolls"),
    BERN("BERNcash"),
    BERRY("Rentberry"),
    BEST("BestChain"),
    BET("BetaCoin"),
    BETR("BetterBetting"),
    BETT("Bettium"),
    BEX("BEX token"),
    BEZ("Bezop"),
    BFDT("Befund"),
    BFT("BF Token"),
    BFX("BitFinex Tokens"),
    BGL("Buglab"),
    BHC("BlackholeCoin"),
    BIC("Bikercoins"),
    BID("BidCoin"),
    BIFI("BitcoinFile"),
    BIGUP("BigUp"),
    BIM("BitminerCoin"),
    BINS("Bitsense"),
    BIO("Biocoin"),
    BIOB("BioBar"),
    BIOS("BiosCrypto"),
    BIP("BipCoin"),
    BIS("Bismuth"),
    BIT("BitRewards"),
    BIT16("16BitCoin"),
    BITB("BitBean"),
    BITCAR("BitCar"),
    BITCNY("bitCNY"),
    BITG("Bitcoin Green"),
    BITGOLD("bitGold"),
    BITOK("BitOKX"),
    BITS("BitstarCoin"),
    BITSD("Bits Digit"),
    BITSILVER("bitSilver"),
    BITUSD("bitUSD"),
    BITX("BitScreener"),
    BITZ("Bitz Coin"),
    BIX("BiboxCoin"),
    BKC("Balkancoin"),
    BKX("BANKEX"),
    BLAS("BlakeStar"),
    BLAZR("BlazerCoin"),
    BLC("BlakeCoin"),
    BLITZ("BlitzCoin"),
    BLK("BlackCoin"),
    BLN("Bolenum"),
    BLOCK("BlockNet"),
    BLOCKPAY("BlockPay"),
    BLRY("BillaryCoin"),
    BLT("Bloom Token"),
    BLU("BlueCoin"),
    BLUE("Ethereum Blue"),
    BLX("Blockchain Index"),
    BLZ("Bluzelle"),
    BM("BitMoon"),
    BMC("Blackmoon Crypto"),
    BMH("BlockMesh"),
    BMK("Benchmark"),
    BMT("BMChain"),
    BMX("BitMart Coin"),
    BMXT("Bitmxittz"),
    BNB("Binance Coin"),
    BNC("Benjacoin"),
    BNK("Bankera"),
    BNT("Bancor Network Token"),
    BNTN("Blocnation"),
    BNTY("Bounty0x"),
    BNX("BnrtxCoin"),
    BOAT("Doubloon"),
    BOB("Bob Coin"),
    BOE("Bodhi "),
    BOG("Bogcoin"),
    BOLD("Bold"),
    BOLI("BolivarCoin"),
    BOMB("BombCoin"),
    BON("BonesCoin"),
    BOOM("BOOM Coin"),
    BOS("BOScoin"),
    BOSON("BosonCoin"),
    BOSS("BitBoss"),
    BOST("BoostCoin"),
    BOT("Bodhi"),
    BOTC("BotChain"),
    BOTS("ArkDAO"),
    BOU("Boulle"),
    BOXY("BoxyCoin"),
    BPL("BlockPool"),
    BPT("Blockport"),
    BQ("Bitqy"),
    BQC("BQCoin"),
    BRAIN("BrainCoin"),
    BRAT("BROTHER"),
    BRC("BinaryCoin"),
    BRD("Bread token"),
    BRDD("BeardDollars"),
    BRIA("Briacoin"),
    BRIT("BritCoin"),
    BRK("BreakoutCoin"),
    BRO("Bitradio"),
    BRONZ("BitBronze"),
    BRX("Breakout Stake"),
    BS("BlackShadowCoin"),
    BSC("BowsCoin"),
    BSD("BitSend"),
    BSR("BitSoar Coin"),
    BST("BitStone"),
    BSTAR("Blackstar"),
    BSTK("BattleStake"),
    BSTN("BitStation"),
    BSTY("GlobalBoost"),
    BSX("Bitspace"),
    BT("BuildTeam"),
    BT1("Bitfinex Bitcoin Future"),
    BT2("Bitcoin SegWit2X"),
    BTA("Bata"),
    BTB("BitBar"),
    BTC("Bitcoin"),
    BTCA("Bitair"),
    BTCC("Bitcoin Core"),
    BTCD("BitcoinDark"),
    BTCE("EthereumBitcoin"),
    BTCGO("BitcoinGo"),
    BTCH("Bitcoin Hush"),
    BTCL("BTC Lite"),
    BTCM("BTCMoon"),
    BTCN("BitcoiNote"),
    BTCP("Bitcoin Private"),
    BTCR("BitCurrency"),
    BTCRED("Bitcoin Red"),
    BTCRY("BitCrystal"),
    BTCS("Bitcoin Scrypt"),
    BTCZ("BitcoinZ"),
    BTD("Bitcloud"),
    BTDX("Bitcloud 2.0"),
    BTE("ByteCoin"),
    BTF("Blockchain Traded Fund"),
    BTG("Bitcoin Gold"),
    BTH("Bytether "),
    BTL("Bitrolium"),
    BTLC("BitLuckCoin"),
    BTM("Bytom"),
    BTMI("BitMiles"),
    BTN("Bitcoin Nova"),
    BTO("Bottos"),
    BTPL("Bitcoin Planet"),
    BTQ("BitQuark"),
    BTRM("Betrium Token"),
    BTRN("Biotron"),
    BTS("Bitshares"),
    BTT("Blocktrade token"),
    BTTF("Coin to the Future"),
    BTW("BitcoinWhite"),
    BTX("Bitcore"),
    BTZ("BitzCoin"),
    BUBO("Budbo"),
    BUK("CryptoBuk"),
    BULLS("BullshitCoin"),
    BUN("BunnyCoin"),
    BURST("BurstCoin"),
    BUZZ("BuzzCoin"),
    BVC("BeaverCoin"),
    BWK("Bulwark"),
    BWS("BitcoinWSpectrum"),
    BWT("Bittwatt"),
    BXC("Bitcedi"),
    BXT("BitTokens"),
    BYC("ByteCent"),
    BZNT("Bezant"),
    C2("Coin.2"),
    C20("Crypto20"),
    CAB("CabbageUnit"),
    CABS("CyberTrust"),
    CACH("Cachecoin"),
    CAG("Change"),
    CAIX("CAIx"),
    CALC("CaliphCoin"),
    CAM("Camcoin"),
    CAN("CanYaCoin"),
    CANDY("UnicornGo Candy"),
    CANN("CannabisCoin"),
    CAP("BottleCaps"),
    CAPP("Cappasity"),
    CAR("CarBlock "),
    CARBON("Carboncoin"),
    CARD("Cardstack"),
    CARE("Carebit"),
    CAS("Cashaa"),
    CASH("CashCoin"),
    CAT("BitClave"),
    CAT1("Catcoin"),
    CAV("Caviar"),
    CBC("CashBet Coin"),
    CBD("CBD Crystals"),
    CBS("Cerberus"),
    CBT("CommerceBlock Token"),
    CBX("CryptoBullion"),
    CC("CyberCoin"),
    CCC("CCCoin"),
    CCN("CannaCoin"),
    CCO("Ccore"),
    CCOS("CrowdCoinage"),
    CCRB("CryptoCarbon"),
    CCT("Crystal Clear Token "),
    CCX("CoolDarkCoin"),
    CDN("Canada eCoin"),
    CDT("Blox"),
    CDX("Cryptodex"),
    CDY("Bitcoin Candy"),
    CEDEX("CEDEX Coin"),
    CEEK("CEEK Smart VR Token"),
    CEFS("CryptopiaFeeShares"),
    CEL("Celsius Network"),
    CELL("SolarFarm"),
    CESC("Crypto Escudo"),
    CET("CoinEx token"),
    CETI("CETUS Coin"),
    CF("Californium"),
    CFC("CoffeeCoin"),
    CFD("Confido"),
    CFI("Cofound.it"),
    CFT("CryptoForecast"),
    CFTY("Crafty"),
    CGA("Cryptographic Anomaly"),
    CHA("Charity Coin"),
    CHAN("ChanCoin"),
    CHAO("23 Skidoo"),
    CHARM("Charm Coin"),
    CHASH("CleverHash"),
    CHAT("ChatCoin"),
    CHBR("CryptoHub"),
    CHC("ChainCoin"),
    CHESS("ChessCoin"),
    CHF("MobileBridge Momentum"),
    CHFN("NOKU CHF"),
    CHI("Chimaera"),
    CHIEF("TheChiefCoin"),
    CHILD("ChildCoin"),
    CHIP("Chip"),
    CHIPS("CHIPS"),
    CHOOF("ChoofCoin"),
    CHP("CoinPoker Token"),
    CHSB("SwissBorg"),
    CHT("Countinghouse Fund"),
    CIF("Crypto Improvement Fund"),
    CIN("CinderCoin"),
    CINNI("CINNICOIN"),
    CIR("CircuitCoin"),
    CIRC("CryptoCircuits"),
    CIX("Cryptonetix"),
    CJ("CryptoJacks"),
    CJC("CryptoJournal"),
    CJT("ConnectJob Token"),
    CKC("Clockcoin"),
    CL("CoinLancer"),
    CLAM("CLAMS"),
    CLD("Cloud"),
    CLICK("Clickcoin"),
    CLIN("Clinicoin"),
    CLINT("Clinton"),
    CLN("Colu Local Network"),
    CLO("Callisto Network"),
    CLOAK("CloakCoin"),
    CLOUT("Clout"),
    CLR("CopperLark"),
    CLUB(" ClubCoin"),
    CLUD("CludCoin"),
    CLV("CleverCoin"),
    CMC("CosmosCoin"),
    CMCT("Crowd Machine"),
    CMM("Commercium "),
    CMOS("Cosmo"),
    CMP("Compcoin"),
    CMPCO("CampusCoin"),
    CMS("COMSA"),
    CMT("CyberMiles"),
    CMZ("CRYPTOMAGZ"),
    CNBC("Cash & Back Coin"),
    CNC("ChinaCoin"),
    CND("Cindicator"),
    CNL("ConcealCoin"),
    CNMT("Coinomat"),
    CNN("Content Neutrality Network"),
    CNO("Coino"),
    CNT("Centurion"),
    CNX("Cryptonex"),
    CO2("CO2 Token"),
    COAL("BitCoal"),
    COB("Cobinhood"),
    COC("Community Coin"),
    COE("CoEval"),
    COFI("CoinFi"),
    COG("Cognitio"),
    COI("Coinnec"),
    COIN("Coin"),
    COLX("ColossusCoinXT"),
    COMM("Community Coin"),
    COMP("Compound Coin"),
    CON_("Paycon"),
    CONI("CoinBene"),
    COOL("CoolCoin"),
    COR("Corion"),
    CORAL("CoralPay"),
    CORE("Core Group Asset"),
    COSS("COSS"),
    COU("Couchain"),
    COV("CovenCoin"),
    COVAL("Circuits of Value"),
    COX("CobraCoin"),
    CPAY("CryptoPay"),
    CPC("CapriCoin"),
    CPL("CoinPlace Token"),
    CPN("CompuCoin"),
    CPT("Cryptaur"),
    CPX("Apex Token"),
    CPY("COPYTRACK"),
    CQST("ConquestCoin"),
    CRAB("CrabCoin"),
    CRACK("CrackCoin"),
    CRAFT("Craftcoin"),
    CRAIG("CraigsCoin"),
    CRAVE("CraveCoin"),
    CRB("Creditbit "),
    CRC("CraftCoin"),
    CRDNC("Credence Coin"),
    CRDS("Credits"),
    CRE("Creditcoin"),
    CREA("CreativeChain"),
    CRED("Verify"),
    CREDO("Credo"),
    CREVA("Creva Coin"),
    CRL("Cryptelo Coin"),
    CRM("Cream"),
    CRNK("CrankCoin"),
    CROAT("Croat"),
    CRPS("CryptoPennies"),
    CRPT("Crypterium"),
    CRS("Cryptoreal"),
    CRTM("Cryptum"),
    CRU("Curium"),
    CRW("Crown Coin"),
    CRX("ChronosCoin"),
    CRYPT("CryptCoin"),
    CS("CryptoSpots"),
    CSC("CasinoCoin"),
    CSH("CashOut"),
    CSMIC("Cosmic"),
    CSNO("BitDice"),
    CSTL("Castle"),
    CTC("CarterCoin"),
    CTIC("Coinmatic"),
    CTKN("Curaizon"),
    CTO("Crypto"),
    CTR("Centra"),
    CTT("CodeTract"),
    CTX("CarTaxi"),
    CTXC("Cortex"),
    CUBE("DigiCube"),
    CURE("Curecoin"),
    CUZ("Cool Cousin"),
    CV("CarVertical"),
    CVC("Civic"),
    CVCOIN("Crypviser"),
    CVT("CyberVein"),
    CVTC("CavatCoin"),
    CWIS("Crypto Wisdom Coin"),
    CWV("CryptoWave"),
    CWX("Crypto-X"),
    CWXT("CryptoWorldXToken"),
    CXC("CheckCoin"),
    CXO("CargoX"),
    CXT("Coinonat"),
    CYC("ConSpiracy Coin "),
    CYDER("Cyder Coin"),
    CYG("Cygnus"),
    CYP("CypherPunkCoin"),
    CYT("Cryptokenz"),
    CZC("Crazy Coin"),
    DAC("DACash"),
    DADI("DADI"),
    DAI("Dai"),
    DAN("Daneel"),
    DANK("DarkKush"),
    DAR("Darcrus"),
    DARK("Dark"),
    DARX("Bitdaric"),
    DAS("DAS"),
    DASC("DasCoin"),
    DASH("Dash"),
    DAT("Datum"),
    DATA("Streamr DATAcoin"),
    DATX("DATx"),
    DAV("DavorCoin"),
    DAXX("DaxxCoin"),
    DAY("Chronologic"),
    DB("DarkBit"),
    DBC("DeepBrain Chain"),
    DBET("Decent.bet"),
    DBG("Digital Bullion Gold"),
    DBIC("DubaiCoin"),
    DBIX("DubaiCoin"),
    DBR("Düber"),
    DBTC("DebitCoin"),
    DCC("Distributed Credit Chain"),
    DCK("DickCoin"),
    DCN("Dentacoin"),
    DCR("Decred"),
    DCRE("DeltaCredits"),
    DCS("deCLOUDs"),
    DCT("Decent"),
    DCY("Dinastycoin"),
    DDD("Scry.info"),
    DDF("Digital Developers Fund"),
    DEA("Degas Coin"),
    DEAL("iDealCash"),
    DEB("Debitum Token"),
    DEC("Darico"),
    DEEP("Deep Gold"),
    DEI("Deimos"),
    DEM("eMark"),
    DENT("Dent"),
    DERO("Dero"),
    DES("Destiny"),
    DESI("DESI"),
    DETH("DarkEther"),
    DEUR("DigiEuro"),
    DEV("Deviant Coin"),
    DFBT("DentalFix"),
    DFS("DFSCoin"),
    DFT("Draftcoin"),
    DGB("DigiByte"),
    DGC("DigiCoin"),
    DGD("Digix DAO"),
    DGDC("DarkGold"),
    DGM("DigiMoney"),
    DGMS("Digigems"),
    DGORE("DogeGoreCoin"),
    DGPT("DigiPulse"),
    DGX("Digix Gold token"),
    DHT("DeHedge Token"),
    DICE("Etheroll"),
    DIEM("CarpeDiemCoin"),
    DIG("Dignity"),
    DIGIF("DigiFel"),
    DIGS("Diggits"),
    DIM("DIMCOIN"),
    DIME("DimeCoin"),
    DIN("Dinero"),
    DISK("Dark Lisk"),
    DIT("Ditcoin"),
    DIVX("Divi"),
    DIW("DIWtoken"),
    DKC("DarkKnightCoin"),
    DKD("Dekado"),
    DLC("DollarCoin"),
    DLISK("Dlisk"),
    DLR("DollarOnline"),
    DLT("Agrello Delta"),
    DMD("Diamond"),
    DML("Decentralized Machine Learning"),
    DMT("DMarket"),
    DNA("EncrypGen"),
    DNET("Darknet"),
    DNN("DNN Token"),
    DNO("Denaro"),
    DNR("Denarius"),
    DNT("district0x"),
    DOC("Doc Coin"),
    DOCK("Dock.io"),
    DOGE("Dogecoin"),
    DOGED("DogeCoinDark"),
    DOGETH("EtherDoge"),
    DON("DonationCoin"),
    DOPE("DopeCoin"),
    DOR("Dorado"),
    DOT("Dotcoin"),
    DOVU("DOVU"),
    DOW("DowCoin"),
    DP("DigitalPrice"),
    DPAY("DelightPay"),
    DPP("Digital Assets Power Play"),
    DRA("DraculaCoin"),
    DRACO("DT Token"),
    DRC("Dropcoin"),
    DREAM("DreamTeam Token"),
    DRG("Dragon Coin"),
    DRGN("Dragonchain"),
    DRKC("DarkCash"),
    DRKT("DarkTron"),
    DRM8("Dream8Coin"),
    DROP("FaucetCoin"),
    DRP("DCORP"),
    DRPU("DRP Utility"),
    DRS("Digital Rupees"),
    DRT("DomRaider"),
    DRXNE("Droxne"),
    DRZ("Droidz"),
    DSB("DarkShibe"),
    DSH("Dashcoin"),
    DSR("Desire"),
    DT("DarkToken"),
    DTA("Data"),
    DTB("Databits"),
    DTC("Datacoin"),
    DTCT("DetectorToken"),
    DTEM("Dystem"),
    DTH("Dether"),
    DTR("Dynamic Trading Rights"),
    DTRC("Datarius"),
    DTT("Data Trading"),
    DTX("DataBroker DAO"),
    DUB("DubCoin"),
    DUBI("Decentralized Universal Basic Income"),
    DUCK("DuckDuckCoin"),
    DUO("ParallelCoin"),
    DUTCH("Dutch Coin"),
    DUX("DuxCoin"),
    DVC("DevCoin"),
    DXC("DixiCoin"),
    DXT("DataWallet"),
    DYN("Dynamic"),
    EA("EagleCoin"),
    EAC("EarthCoin"),
    EAGS("EagsCoin"),
    EARTH("Earth Token"),
    EB3("EB3coin"),
    EBC("EBCoin"),
    EBCH("eBitcoinCash"),
    EBET("EthBet"),
    EBIT("eBit"),
    EBS("EbolaShare"),
    EBST("eBoost"),
    EBTC("eBitcoin"),
    EBZ("Ebitz"),
    EC("Eclipse"),
    ECA("Electra"),
    ECASH("Ethereum Cash"),
    ECC("E-CurrencyCoin"),
    ECH("EthereCash"),
    ECHT("e-Chat"),
    ECO("ECOcoin"),
    ECOB("EcoBit"),
    EDC("EducoinV"),
    EDDIE("Eddie coin"),
    EDG("Edgeless"),
    EDGE("EdgeCoin"),
    EDO("Eidoo"),
    EDR("E-Dinar Coin"),
    EDRC("EDRCoin"),
    EDT("EtherDelta"),
    EDU("Educoin"),
    EFIC("FIC Network"),
    EFL("E-Gulden"),
    EFX("The EFFECT Network"),
    EFYT("Ergo"),
    EGAS("ETHGAS"),
    EGC("EverGreenCoin"),
    EGCC("Engine"),
    EGG("EggCoin"),
    EGO("EGOcoin"),
    EGT("Egretia"),
    EJAC("EJA Coin"),
    EKN("Elektron"),
    EKO("EchoLink"),
    ELA("Elastos"),
    ELC("Elacoin"),
    ELE("Elementrem"),
    ELEC("Electrify.Asia"),
    ELF("aelf"),
    ELI("Elicoin"),
    ELITE("EthereumLite"),
    ELIX("Elixir"),
    ELLA("Ellaism"),
    ELLI("ElliotCoin"),
    ELM("Elements"),
    ELP("Ellerium"),
    ELS("Elysium"),
    ELT("Eloplay"),
    ELTC2("eLTC"),
    ELTCOIN("ELTCOIN"),
    ELY("Elysian"),
    EMB("EmberCoin"),
    EMC("Emercoin"),
    EMC2("Einsteinium"),
    EMD("Emerald"),
    EMGO("MobileGo"),
    EMIGR("EmiratesGoldCoin"),
    EMN("Eminent Token "),
    EMPC("EmporiumCoin"),
    EMT("EasyMine"),
    EMV("Ethereum Movie Venture"),
    ENE("EneCoin"),
    ENG("Enigma"),
    ENJ("Enjin Coin"),
    ENK("Enkidu"),
    ENRG("EnergyCoin"),
    ENT("Eternity"),
    ENTER("EnterCoin"),
    ENTRC("ENTER COIN"),
    ENTRP("Entropy Token"),
    ENU("Enumivo"),
    EOC("EveryonesCoin"),
    EON("Exscudo"),
    EOS("EOS"),
    EOSDAC("eosDAC"),
    EPIK("EPIK Token"),
    EPRX("eProxy"),
    EPY("Empyrean"),
    EQ("EQUI"),
    EQB("Equibit"),
    EQL("EQUAL"),
    EQM("Equilibrium Coin"),
    EQT("EquiTrader"),
    EQUAL("EqualCoin"),
    EQUI("EQUI Token"),
    ERB("ERBCoin"),
    ERC("EuropeCoin"),
    ERC20("Index ERC20"),
    EREAL("eREAL"),
    ERO("Eroscoin"),
    ERR("ErrorCoin"),
    ERT("Eristica"),
    ERY("Eryllium"),
    ESC("Ethersportcoin"),
    ESP("Espers"),
    ESS("Essentia"),
    ESZ("EtherSportz"),
    ET4("Eticket4"),
    ETBS("EthBits"),
    ETBT("Ethereum Black"),
    ETC("Ethereum Classic"),
    ETF("EthereumFog"),
    ETG("Ethereum Gold"),
    ETH("Ethereum"),
    ETHB("EtherBTC"),
    ETHD("Ethereum Dark"),
    ETHM("Ethereum Meta"),
    ETHOS("Ethos"),
    ETHPR("Ethereum Premium"),
    ETHS("EthereumScrypt"),
    ETK("Energi Token"),
    ETKN("EasyToken"),
    ETL("EtherLite"),
    ETN("Electroneum"),
    ETP("Metaverse"),
    ETS("ETH Share"),
    ETT("EncryptoTel"),
    ETZ("EtherZero"),
    EUC("Eurocoin"),
    EUNO("EUNO"),
    EURN("NOKU EUR"),
    EVC("Eventchain"),
    EVE("Devery"),
    EVENT("Event Token"),
    EVIL("EvilCoin"),
    EVN("EvenCoin"),
    EVR("Everus"),
    EVX("Everex"),
    EXB("ExaByte"),
    EXC("Eximchain"),
    EXCC("ExchangeCoin"),
    EXCL("Exclusive Coin"),
    EXE("ExeCoin"),
    EXIT("ExitCoin"),
    EXMR("eXMR Monero"),
    EXN("ExchangeN"),
    EXP("Expanse"),
    EXRN("EXRNchain"),
    EXTN("Extensive Coin"),
    EXY("Experty"),
    EZC("EZCoin"),
    EZM("EZMarket"),
    EZT("EZToken"),
    F16("F16Coin"),
    FACE("Faceter "),
    FAIR("FairCoin"),
    FAME("FameCoin"),
    FARM("FARM Coin"),
    FAZZ("FazzCoin"),
    FC("Facecoin"),
    FC2("Fuel2Coin"),
    FCN("FantomCoin "),
    FCS("CryptoFocus"),
    FCT("Factoids"),
    FDX("fidentiaX"),
    FDZ("Friendz"),
    FFC("FireflyCoin"),
    FGZ("Free Game Zone"),
    FIBRE("FIBRE"),
    FIL("FileCoin"),
    FILL("Fillit"),
    FIN("Finom FIN Token"),
    FIND("FindCoin"),
    FIRE("FireCoin"),
    FIRST("FirstCoin"),
    FIST("FistBump"),
    FIT("Fitcoin"),
    FJC("FujiCoin"),
    FLAP("Flappy Coin"),
    FLASH("FLASH coin"),
    FLDC("Folding Coin"),
    FLIK("FLiK"),
    FLIP("BitFlip"),
    FLIXX("Flixxo"),
    FLLW("Follow Coin"),
    FLM("FOLM coin"),
    FLO("FlorinCoin"),
    FLOT("FireLotto"),
    FLP("Gameflip"),
    FLS("Fuloos Coin"),
    FLT("FlutterCoin"),
    FLUZ("FluzFluz"),
    FLVR("FlavorCoin"),
    FLX("BitFlux"),
    FLY("FlyCoin"),
    FND("FundRequest"),
    FNO("Fonero"),
    FNP("FlipNpik"),
    FNTB("FinTab"),
    FONZ("FonzieCoin"),
    FOOD("FoodCoin"),
    FOPA("Fopacoin"),
    FOR("Force Coin"),
    FOREX("ForexCoin"),
    FOTA("Fortuna"),
    FOXT("Fox Trading"),
    FRAC("FractalCoin"),
    FRAZ("FrazCoin"),
    FRC("FireRoosterCoin"),
    FRD("Farad"),
    FRE("FreeCoin"),
    FREC("Freyrchain"),
    FREE("FREE coin"),
    FRK("Franko"),
    FRN("Francs"),
    FRST("FirstCoin"),
    FRV("Fitrova"),
    FRWC("Frankywillcoin"),
    FSBT("Forty Seven Bank"),
    FSC("FriendshipCoin"),
    FSN("Fusion"),
    FST("FastCoin"),
    FT("Fabric Token"),
    FTC("FeatherCoin"),
    FTO("FuturoCoin"),
    FTP("FuturePoints"),
    FTW("FutureWorks"),
    FTX("FintruX"),
    FUCK("Fuck Token"),
    FUEL("Etherparty"),
    FUN("FunFair"),
    FUNC("FunCoin"),
    FUND("Fund Platform"),
    FUNK("Cypherfunks Coin"),
    FUTC("FutCoin"),
    FUZZ("Fuzzballs"),
    FX("FCoin"),
    FXT("FuzeX"),
    FYN("FundYourselfNow"),
    FYP("FlypMe"),
    GAI("GraphGrail AI"),
    GAIA("GAIA Platform"),
    GAKH("GAKHcoin"),
    GAM("Gambit coin"),
    GAME("Gamecredits"),
    GAP("Gapcoin"),
    GAS("Gas"),
    GAT("GATCOIN"),
    GB("GoldBlocks"),
    GBG("Golos Gold"),
    GBIT("GravityBit"),
    GBRC("GBR Coin"),
    GBT("GameBetCoin"),
    GBX("GoByte"),
    GBYTE("Byteball"),
    GCC("GuccioneCoin"),
    GCN("gCn Coin"),
    GCR("Global Currency Reserve"),
    GDC("GrandCoin"),
    GEA("Goldea"),
    GEM("Gems"),
    GEMZ("Gemz Social"),
    GEN("Genstake"),
    GENE("PARKGENE"),
    GEO("GeoCoin"),
    GER("GermanCoin"),
    GES("Galaxy eSolutions"),
    GET("Guaranteed Entrance Token"),
    GETX("Guaranteed Ethurance Token Extra"),
    GEX("GreenX"),
    GFT("Giftcoin"),
    GGS("Gilgam"),
    GHC("GhostCoin"),
    GHOUL("Ghoul Coin"),
    GHS("Giga Hash"),
    GIC("Giant"),
    GIFT("GiftNet"),
    GIG("GigCoin"),
    GIM("Gimli"),
    GIN("GINcoin"),
    GIVE("GiveCoin"),
    GIZ("GIZMOcoin"),
    GJC("Global Jobcoin"),
    GLA("Gladius"),
    GLC("GlobalCoin"),
    GLD("GoldCoin"),
    GLOBE("Global"),
    GLT("GlobalToken"),
    GLX("GalaxyCoin"),
    GLYPH("GlyphCoin"),
    GMC("Gridmaster"),
    GMCN("GambleCoin"),
    GML("GameLeagueCoin"),
    GMR("Gimmer"),
    GMT("Mercury Protocol"),
    GMX("Goldmaxcoin"),
    GNJ("GanjaCoin V2"),
    GNO("Gnosis"),
    GNR("Gainer"),
    GNT("Golem Network Token"),
    GNX("Genaro Network"),
    GO("GoChain"),
    GOA("GoaCoin"),
    GOAL("Goal Bonanza"),
    GOAT("Goat"),
    GOLF("GolfCoin"),
    GOLOS("Golos"),
    GOOD("GoodCoin"),
    GOON("Goonies"),
    GOT("Giotto Coin"),
    GOTX("GothicCoin"),
    GP("GoldPieces"),
    GPL("Gold Pressed Latinum"),
    GPU("GPU Coin"),
    GRAM("Telegram Open Network"),
    GRAV("Graviton"),
    GRC("GridCoin"),
    GRE("GreenCoin"),
    GREXIT("GrexitCoin"),
    GRFT("Graft Blockchain"),
    GRID("GridPay"),
    GRLC("Garlicoin"),
    GRM("GridMaster"),
    GRMD("GreenMed"),
    GRO("Gron Digital"),
    GROW("GrownCoin"),
    GRS("Groestlcoin "),
    GRW("GrowthCoin"),
    GRWI("Growers International"),
    GRX("Gold Reward Token"),
    GSC("Global Social Chain"),
    GSI("Globex SCI"),
    GSM("GSM Coin"),
    GST("Gostcoin"),
    GSX("GlowShares"),
    GSY("GenesysCoin"),
    GTC("Global Tour Coin"),
    GTO("GIFTO"),
    GUE("GuerillaCoin"),
    GUESS("Peerguess"),
    GUN("GunCoin"),
    GUNS("GeoFunders"),
    GUP("Guppy"),
    GVT("Genesis Vision"),
    GX("GameX"),
    GXC("GenXCoin"),
    GXS("GXChain"),
    H2O("Hydrominer"),
    HAC("Hackspace Capital"),
    HADE("Hade Token"),
    HAL("Halcyon"),
    HALAL("Halal"),
    HALLO("Halloween Coin"),
    HALO("Halo Platform"),
    HAMS("HamsterCoin"),
    HAT("Hawala.Today"),
    HAV("Havven"),
    HAZE("HazeCoin"),
    HB("HeartBout"),
    HBC("HomeBlockCoin"),
    HBN("HoboNickels"),
    HBT("Hubii Network"),
    HBZ("Helbiz"),
    HCC("HappyCreatorCoin "),
    HDG("Hedge Token"),
    HEAT("Heat Ledger"),
    HEDG("Hedgecoin"),
    HEEL("HeelCoin"),
    HELL("HELL COIN"),
    HER("Hero Node"),
    HERO("Hero"),
    HEX("HexCoin"),
    HFT("Hirefreehands"),
    HGS("HashGains"),
    HGT("Hello Gold"),
    HHEM("Healthureum"),
    HILL("President Clinton"),
    HION("Handelion"),
    HIRE("BitHIRE"),
    HIVE("Hive"),
    HKG("Hacker Gold"),
    HKN("Hacken"),
    HLC("Halal-Chain"),
    HLP("Purpose Coin"),
    HMC("Hi Mutual Society"),
    HMP("HempCoin"),
    HMQ("Humaniq"),
    HMT("Hamster Marketplace Token"),
    HNC("Huncoin"),
    HODL("HOdlcoin"),
    HOLD("Interstellar Holdings"),
    HONEY("Honey"),
    HORSE("Ethorse "),
    HOT("Hydro Protocol"),
    HPB("High Performance Blockchain"),
    HPC("HappyCoin"),
    HQX("HOQU"),
    HRB("Harbour DAO"),
    HSC("HashCoin "),
    HSP("Horse Power"),
    HSR("Hshare"),
    HST("Decision Token"),
    HT("Huobi Token"),
    HTC("Hitcoin"),
    HTML("HTML Coin"),
    HTML5("HTML5 Coin"),
    HUC("HunterCoin"),
    HUGE("BigCoin"),
    HUR("Hurify"),
    HUSH("Hush"),
    HVC("HeavyCoin"),
    HVCO("High Voltage Coin"),
    HVN("Hive Project"),
    HWC("HollyWoodCoin"),
    HXT("HextraCoin"),
    HXX("HexxCoin"),
    HYDRO("Hydrogen"),
    HYP("Hyperstake"),
    HYPER("HyperCoin"),
    HYS("Heiss Shares"),
    HYT("HoryouToken"),
    HZ("Horizon"),
    HZT("HazMatCoin"),
    I0C("I0coin"),
    IBANK("iBankCoin"),
    IC("Ignition"),
    ICASH("ICASH"),
    ICB("IceBergCoin"),
    ICC("Insta Cash Coin"),
    ICE("iDice"),
    ICN("Iconomi"),
    ICOB("Icobid"),
    ICON("Iconic"),
    ICOO("ICO OpenLedger"),
    ICOS("ICOBox"),
    ICST("ICST"),
    ICX("ICON Project"),
    IDH("IndaHash"),
    IDXM("IDEX Membership"),
    IEC("IvugeoEvolutionCoin"),
    IETH("iEthereum"),
    IFC("Infinite Coin"),
    IFLT("InflationCoin"),
    IFT("InvestFeed"),
    IFX("Infinex"),
    IGNIS("Ignis"),
    IHT("I-House Token"),
    ILC("ILCoin"),
    ILCT("ILCoin Token"),
    ILK("Inlock"),
    ILT("iOlite"),
    IML("IMMLA"),
    IMPCH("Impeach"),
    IMPS("Impulse Coin"),
    IMS("Independent Money System"),
    IMV("ImmVRse"),
    IMX("Impact"),
    IN("InCoin"),
    INC("Incrementum"),
    INCNT("Incent"),
    INCP("InceptionCoin"),
    IND("Indorse"),
    INDI("IndiCoin"),
    INF8("Infinium-8"),
    INFX("Influxcoin"),
    ING("Iungo"),
    INK("Ink"),
    INN("Innova"),
    INPAY("InPay"),
    INS("INS Ecosystem"),
    INSANE("InsaneCoin"),
    INSN("Insane Coin"),
    INSTAR("Insights Network"),
    INSUR("InsurChain Coin"),
    INT("Internet Node Token"),
    INTO("Influ Token"),
    INV("Invictus"),
    INVOX("Invox Finance"),
    INXT("Internxt"),
    IOC("IOCoin"),
    ION("Ionomy"),
    IOP("Internet of People"),
    IOST("IOS token"),
    IOT("IOTA"),
    IOTX("IoTeX Network"),
    IOU("IOU1"),
    IPC("ImperialCoin"),
    IPL("InsurePal"),
    IPSX("IP Exchange"),
    IQ("Everipedia"),
    IQB("Intelligence Quotient Benefit"),
    IRC("IRONCOIN"),
    IRL("IrishCoin"),
    ISL("IslaCoin"),
    ITA("Italocoin"),
    ITC("IoT Chain"),
    ITM("intimate.io"),
    ITNS("IntenseCoin"),
    ITT("Intelligent Trading"),
    ITZ("Interzone"),
    IVY("IvyKoin"),
    IVZ("InvisibleCoin"),
    IW("iWallet"),
    IWT("IwToken"),
    IXC("IXcoin"),
    IXT("iXledger"),
    J("JoinCoin"),
    J8T("JET8"),
    JANE("JaneCoin"),
    JBS("JumBucks Coin"),
    JC("JesusCoin"),
    JCR("Jincor"),
    JDC("JustDatingSite"),
    JET("Jetcoin"),
    JEW("Shekel"),
    JEX("JEX Token"),
    JIF("JiffyCoin"),
    JINN("Jinn"),
    JIO("JIO Token"),
    JKC("JunkCoin"),
    JNS("Janus"),
    JNT("Jibrel Network Token"),
    JOBS("JobsCoin"),
    JOINT("Joint Ventures"),
    JOK("JokerCoin"),
    JOY("JoyToken"),
    JPC("JackPotCoin"),
    JTX("Project J"),
    JUDGE("JudgeCoin"),
    JUMP("Jumpcoin"),
    JVY("Javvy"),
    JWL("Jewels"),
    KAAS("KAASY.AI"),
    KAPU("Kapu"),
    KARMA("Karmacoin"),
    KAT("KATZcoin"),
    KAYI("Kayı"),
    KB3("B3Coin"),
    KBC("Karatgold coin"),
    KBR("Kubera Coin"),
    KC("Kernalcoin"),
    KCS("Kucoin"),
    KDC("Klondike Coin"),
    KEC("KEYCO"),
    KED("Klingon Empire Darsek"),
    KEK("KekCoin"),
    KEN("Kencoin"),
    KEP("Kepler"),
    KETAN("Ketan"),
    KEX("KexCoin"),
    KEY("KeyCoin"),
    KGC("KrugerCoin"),
    KICK("KickCoin"),
    KIN("Kin"),
    KIND("Kind Ads"),
    KING("King93"),
    KLC("KiloCoin"),
    KLKS("Kalkulus"),
    KMD("Komodo"),
    KNC("Kyber Network"),
    KNG("BetKings"),
    KNW("Knowledge "),
    KOBO("KoboCoin"),
    KOLION("Kolion"),
    KORE("Kore"),
    KR("Krypton"),
    KRAK("Kraken"),
    KRB("Karbo"),
    KRC("KRCoin"),
    KREDS("KREDS"),
    KRL("Kryll"),
    KRM("Karma"),
    KRONE("Kronecoin"),
    KRX("RAVN Korrax "),
    KTK("KryptCoin"),
    KUBO("KubosCoin"),
    KURT("Kurrent"),
    KUSH("KushCoin"),
    KWH("KWHCoin"),
    KZC("KZCash"),
    LA("LATOKEN"),
    LAB("Labrys"),
    LALA("LaLa World"),
    LANA("LanaCoin"),
    LAT("Latium"),
    LATX("LatiumX"),
    LAZ("Lazarus"),
    LBA("Libra Credit"),
    LBC("LBRY Credits"),
    LBTC("LiteBitcoin"),
    LC("Lutetium Coin"),
    LCASH("LitecoinCash"),
    LCC("LitecoinCash"),
    LCK("Luckbox"),
    LCP("Litecoin Plus"),
    LCS("LocalCoinSwap"),
    LCT("LendConnect"),
    LCWP("LiteCoinW Plus"),
    LDC("LeadCoin"),
    LDM("Ludum token"),
    LDN("Lydiancoin"),
    LDOGE("LiteDoge"),
    LEA("LeaCoin"),
    LEAF("LeafCoin"),
    LEDU("Education Ecosystem"),
    LELE("Lelecoin"),
    LEMON("LemonCoin"),
    LEND("EthLend"),
    LENIN("LeninCoin"),
    LEO("LEOcoin"),
    LEPEN("LePenCoin"),
    LET("LinkEye"),
    LEU("CryptoLEU"),
    LEV("Leverj"),
    LFC("BigLifeCoin"),
    LGBTQ("LGBTQoin"),
    LGD("Legendary Coin"),
    LGO("Legolas Exchange"),
    LGR("Logarithm"),
    LHC("LHCoin"),
    LIF("Winding Tree"),
    LIFE("LIFE"),
    LIGER("Ligercoin"),
    LIKE("LikeCoin"),
    LIMX("LimeCoinX"),
    LINDA("Linda"),
    LINK("ChainLink"),
    LINX("Linx"),
    LION("CoinLion"),
    LIPC("LIpcoin"),
    LIR("Let it Ride"),
    LIV("LiviaCoin"),
    LIVE("Live Stars"),
    LIZ("Lizus Payment"),
    LK7("Lucky7Coin"),
    LKK("Lykke"),
    LKY("LuckyCoin"),
    LMC("LomoCoin"),
    LNC("Linker Coin"),
    LND("Lendingblock"),
    LNK("Ethereum.Link"),
    LOAN("Lendoit"),
    LOC("LockTrip"),
    LOCI("LociCoin"),
    LOG("Wood Coin"),
    LOKI("Loki"),
    LOOK("LookCoin"),
    LOOM("Loom Network"),
    LOT("LottoCoin"),
    LQD("Liquid"),
    LRC("Loopring"),
    LSD("LightSpeedCoin"),
    LSK("Lisk"),
    LST("Lendroid Support Token"),
    LTA("Litra"),
    LTB("Litebar "),
    LTBC("LTBCoin"),
    LTC("Litecoin"),
    LTCC("Listerclassic Coin"),
    LTCD("LitecoinDark"),
    LTCH("Litecoin Cash"),
    LTCR("LiteCreed"),
    LTCU("LiteCoin Ultra"),
    LTCX("LitecoinX"),
    LTD("Limited Coin"),
    LTG("LiteCoin Gold"),
    LTH("Lathaan"),
    LTS("Litestar Coin"),
    LUC("Play 2 Live"),
    LUCKY("LuckyBlocks"),
    LUN("Lunyr"),
    LUX("BitLux"),
    LVG("Leverage Coin"),
    LVL("LevelNet Token"),
    LWF("Local World Forwarders"),
    LXC("LibrexCoin"),
    LYB("LyraBar"),
    LYC("LycanCoin"),
    LYK("Loyakk Vega"),
    LYL("LoyalCoin"),
    LYM("Lympo"),
    LYNX("Lynx"),
    M1("SupplyShock"),
    MAC("MachineCoin"),
    MAD("SatoshiMadness"),
    MAG("Magnet"),
    MAID("MaidSafe Coin"),
    MAN("Matrix AI Network"),
    MANA("Decentraland"),
    MANNA("Manna"),
    MAPC("MapCoin"),
    MAR("MarijuanaCoin"),
    MARS("MarsCoin "),
    MARV("Marvelous"),
    MARX("MarxCoin"),
    MARYJ("MaryJane Coin"),
    MASP("Market.space"),
    MASS("Mass.Cloud"),
    MAT("Manet Coin"),
    MAX("MaxCoin"),
    MAY("Theresa May Coin"),
    MBC("My Big Coin"),
    MBI("Monster Byte Inc"),
    MBIT("Mbitbooks"),
    MBLC("Mont Blanc"),
    MBRS("Embers"),
    MBT("Multibot"),
    MC("Mass Coin"),
    MCAP("MCAP"),
    MCAR("MasterCar"),
    MCI("Musiconomi"),
    MCN("MonetaVerde"),
    MCO("Monaco"),
    MCRN("MacronCoin"),
    MCT("1717 Masonic Commemorative Token"),
    MCU("MediChain"),
    MCV("MCV Token"),
    MDA("Moeda"),
    MDC("MadCoin"),
    MDL("Modulum"),
    MDS("MediShares"),
    MDT("Measurable Data Token "),
    MDX("Midex"),
    MEC("MegaCoin"),
    MED("MediterraneanCoin"),
    MEDI("MediBond"),
    MEDIC("MedicCoin"),
    MEDX("Mediblock"),
    MEE("CoinMeet"),
    MEET("CoinMeet"),
    MEGA("MegaFlash"),
    MEME("Pepe"),
    MEOW("Kittehcoin"),
    MER("Mercury"),
    MET("Metronome"),
    METAL("MetalCoin"),
    MFG("SyncFab"),
    MFT("Mainframe"),
    MG("Mind Gene"),
    MGD("MassGrid"),
    MGN("MagnaCoin"),
    MGO("MobileGo"),
    MI("XiaoMiCoin"),
    MIC("Mindexcoin"),
    MIL("Milllionaire Coin"),
    MILO("MiloCoin"),
    MIN("Minerals Coin"),
    MINE("Instamine Nuggets"),
    MINEX("Minex"),
    MINT("MintCoin"),
    MIO("Miner One token"),
    MIS("MIScoin"),
    MITH("Mithril"),
    MITX("Morpheus Infrastructure Token"),
    MIV("MakeItViral"),
    MKR("Maker"),
    MLITE("MeLite"),
    MLN("Melon"),
    MLS("CPROP"),
    MLT("MultiGames"),
    MM("MasterMint"),
    MMC("MemoryCoin"),
    MMNXT("MMNXT "),
    MMO("MMOCoin"),
    MMXIV("MaieutiCoin"),
    MMXVI("MMXVI"),
    MN("Cryptsy Mining Contract"),
    MNB("MoneyBag"),
    MNC("MinCoin"),
    MND("MindCoin"),
    MNE("Minereum"),
    MNM("Mineum"),
    MNT("Media Network Coin"),
    MNTP("GoldMint"),
    MNTS("Mint"),
    MNX("MinexCoin"),
    MNY("Monkey"),
    MNZ("Monaize"),
    MOAT("Mother Of All Tokens"),
    MOBI("Mobius"),
    MOD("Modum"),
    MOIN("MoinCoin"),
    MOJO("Mojocoin"),
    MONA("MonaCoin"),
    MONETA("Moneta"),
    MONEY("MoneyCoin"),
    MONK("Monkey Project"),
    MOON("MoonCoin"),
    MOOND("Dark Moon"),
    MOS("MOS Coin"),
    MOT("Olympus Labs"),
    MOTO("Motocoin"),
    MPRO("MediumProject"),
    MPT("Media Protocol Token"),
    MRK("MARK.SPACE"),
    MRN("Mercoin"),
    MRP("MorpheusCoin"),
    MRPH("Morpheus Network"),
    MRS("MarsCoin"),
    MRSA("MrsaCoin"),
    MRT("MinersReward"),
    MRV("Macroverse"),
    MRY("MurrayCoin"),
    MSC("MasterCoin"),
    MSP("Mothership"),
    MSR("Masari"),
    MST("MustangCoin"),
    MT("Mycelium Token"),
    MTC("DOCADEMIC"),
    MTH("Monetha"),
    MTK("Moya Token"),
    MTL("Metal"),
    MTLM3("Metal Music v3"),
    MTN("Medicalchain"),
    MTR("MasterTraderCoin"),
    MTRC("ModulTrade"),
    MTX("Matryx"),
    MUDRA("MudraCoin"),
    MUE("MonetaryUnit"),
    MUN("MUNcoin"),
    MUSD("MUSDcoin"),
    MUSE("Muse"),
    MUSIC("Musicoin"),
    MUT("Mutual Coin"),
    MUU("MilkCoin"),
    MVP("Merculet"),
    MWAT("RED MegaWatt"),
    MWC("MultiWallet Coin"),
    MXT("MartexCoin"),
    MYB("MyBit"),
    MYC("MayaCoin"),
    MYST("MysteryCoin"),
    MZC("MazaCoin"),
    MZX("Mosaic Network"),
    N7("Number7"),
    NAMO("NamoCoin"),
    NAN("NanoToken"),
    NANAS("BananaBits"),
    NANJ("NANJCOIN"),
    NANO("Nano"),
    NAS("Nebulas"),
    NAS2("Nas2Coin"),
    NAUT("Nautilus Coin"),
    NAV("NavCoin"),
    NAVI("NaviAddress"),
    NBAI("Nebula AI"),
    NBC("Niobium"),
    NBIT("NetBit"),
    NBL("Nybble"),
    NBR("Niobio Cash"),
    NBT("NuBits"),
    NBX("Noxbox"),
    NCASH("Nucleus Vision"),
    NCP("Newton Coin"),
    NCT("PolySwarm"),
    NDC("NeedleCoin"),
    NDOGE("NinjaDoge"),
    NEBL("Neblio"),
    NEBU("Nebuchadnezzar"),
    NEC("NeoCoin"),
    NEF("NefariousCoin"),
    NEO("NEO"),
    NEOG("NEO Gold"),
    NEOS("NeosCoin"),
    NET("NetCoin"),
    NETC("NetworkCoin"),
    NETKO("Netko"),
    NEU("NeuCoin"),
    NEVA("NevaCoin"),
    NEWB("Newbium"),
    NEXO("NEXO"),
    NEXT("Next.exchange Token"),
    NFN("Nafen"),
    NGC("NagaCoin"),
    NIC("NewInvestCoin"),
    NICE("NiceCoin"),
    NIHL("Nihilo Coin"),
    NIMFA("Nimfamoney"),
    NIO("Autonio"),
    NIX("NIX"),
    NKA("IncaKoin"),
    NKC("Nukecoinz"),
    NKN("NKN"),
    NKT("NakomotoDark"),
    NLC("NoLimitCoin"),
    NLC2("NoLimitCoin"),
    NLG("Gulden"),
    NLX("Nullex"),
    NMB("Nimbus Coin"),
    NMC("Namecoin"),
    NMR("Numeraire"),
    NMS("Numus"),
    NOAH("NOAHCOIN"),
    NOBL("NobleCoin"),
    NODE("Node"),
    NOKU("NOKU Master token"),
    NOM("Finom NOM Token"),
    NOO("Noocoin"),
    NOTE("Dnotes"),
    NOX("NITRO"),
    NPC("NPCcoin"),
    NPX("Napoleon X"),
    NPXS("Pundi X"),
    NRB("NoirBits"),
    NRC("Neurocoin"),
    NRN("Doc.ai Neuron"),
    NRO("Neuro"),
    NRS("NoirShares"),
    NSR("NuShares"),
    NTC("NineElevenTruthCoin"),
    NTCC("NeptuneClassic"),
    NTK("Neurotoken"),
    NTM("NetM"),
    NTO("Fujinto"),
    NTRN("Neutron"),
    NTWK("Network Token"),
    NUBIS("NubisCoin"),
    NUKE("NukeCoin"),
    NULS("Nuls"),
    NUM("NumbersCoin"),
    NVC("NovaCoin"),
    NVST("NVO"),
    NWCN("NowCoin"),
    NXC("Nexium"),
    NXE("NXEcoin"),
    NXS("Nexus"),
    NXT("Nxt"),
    NXTI("NXTI"),
    NXTTY("NXTTY"),
    NYAN("NyanCoin"),
    NYC("NewYorkCoin"),
    NYX("NYXCOIN"),
    NZC("NewZealandCoin"),
    NZL("Zealium"),
    OAK("Acorn Collective"),
    OAX("OpenANX"),
    OBITS("Obits Coin"),
    OBS("Obscurebay"),
    OC("OrangeCoin"),
    OCC("Original Crypto Coin"),
    OCL("Oceanlab"),
    OCN("Odyssey"),
    OCT("OracleChain"),
    OCTO("OctoCoin"),
    ODE("ODEM "),
    ODMC("ODMCoin"),
    ODN("Obsidian"),
    ODNT("Old Dogs New Tricks"),
    OIO("Online"),
    OK("OKCash"),
    OKOIN("OKOIN"),
    OLDSF("OldSafeCoin"),
    OLT("OneLedger"),
    OLV("OldV"),
    OLYMP("OlympCoin"),
    OMA("OmegaCoin"),
    OMC("OmniCron"),
    OMG("OmiseGo"),
    OMGC("OmiseGO Classic"),
    OMNI("Omni"),
    OMX("Project Shivom"),
    ONG("onG.social"),
    ONION("DeepOnion"),
    ONL("On.Live"),
    ONT("Ontology"),
    ONX("Onix"),
    OOT("Utrum"),
    OPAL("OpalCoin"),
    OPC("OP Coin"),
    OPEN("Open Platform"),
    OPES("Opes"),
    OPP("Opporty"),
    OPT("Opus"),
    OPTION("OptionCoin"),
    ORB("Orbitcoin"),
    ORE("Galactrum"),
    ORGT("Organic Token"),
    ORI("Origami"),
    ORLY("OrlyCoin"),
    ORME("Ormeus Coin"),
    ORO("OroCoin"),
    OROC("Orocrypt"),
    ORS("ORS SA"),
    OS76("OsmiumCoin"),
    OSA("Optimal Shelf Availability Token"),
    OSC("OpenSourceCoin"),
    OST("Simple Token"),
    OTN("Open Trading Network"),
    OTX("Octanox"),
    OWD("Owlstand"),
    OXY("Oxycoin"),
    OYS("Oyster Platform"),
    PAI("Project Pai"),
    PAK("Pakcoin"),
    PAL("PolicyPal Network"),
    PAN("Pantos"),
    PAR("Parlay"),
    PARA("ParanoiaCoin"),
    PARETO("Pareto Network Token"),
    PART("Particl"),
    PAS("Passive Coin"),
    PASC("Pascal Coin"),
    PASL("Pascal Lite"),
    PAT("PATRON"),
    PAVO("Pavocoin"),
    PAXEX("PAXEX"),
    PAY("TenX"),
    PAYP("PayPeer"),
    PBC("PabyosiCoin"),
    PBL("Publica"),
    PBT("Primalbase"),
    PCL("Peculium"),
    PCM("Procom"),
    PCN("PeepCoin"),
    PCO("Pecunio"),
    PCOIN("Pioneer Coin"),
    PCS("Pabyosi Coin"),
    PDC("Project Decorum"),
    PEC("PeaceCoin"),
    PEN("PenCoin"),
    PEPECASH("Pepe Cash"),
    PERU("PeruCoin"),
    PEX("PosEx"),
    PF("PROVER"),
    PFR("PayFair"),
    PGC("Pegascoin"),
    PGL("Prospectors"),
    PGN("Pigeoncoin"),
    PGT("Puregold token"),
    PHC("Profit Hunters Coin"),
    PHI("PHI Token"),
    PHO("Photon"),
    PHR("Phreak"),
    PHS("PhilosophersStone"),
    PIE("Persistent Information Exchange"),
    PIGGY("Piggy Coin"),
    PING("CryptoPing"),
    PINK("PinkCoin"),
    PINKX("PantherCoin"),
    PIO("Pioneershares"),
    PIRL("Pirl"),
    PITCH("PITCH"),
    PIVX("Private Instant Verified Transaction"),
    PIX("Lampix"),
    PIZZA("PizzaCoin"),
    PKB("ParkByte"),
    PKC("Pikciochain"),
    PKT("Playkey"),
    PLANET("PlanetCoin"),
    PLAY("HEROcoin"),
    PLBT("Polybius"),
    PLC("PlatinCoin"),
    PLM("Algo.Land"),
    PLMT("Pallium"),
    PLNC("PLNCoin"),
    PLR("Pillar"),
    PLU("Pluton"),
    PLURA("PluraCoin"),
    PLUS1("PlusOneCoin"),
    PLX("PlexCoin"),
    PMA("PumaPay"),
    PMNT("Paymon"),
    PNC("PlatiniumCoin"),
    PND("PandaCoin"),
    PNK("SteamPunk"),
    PNT("Penta"),
    PNX("PhantomX"),
    PNY("Peony Coin"),
    POA("Poa Network"),
    POE("Po.et"),
    POINTS("Cryptsy Points"),
    POKER("PokerCoin"),
    POLIS("PolisPay"),
    POLL("ClearPoll"),
    POLY("Polymath Network"),
    POP("PopularCoin"),
    POS("PoSToken"),
    POSQ("Poseidon Quark"),
    POST("PostCoin"),
    POT("PotCoin"),
    POWR("Power Ledger"),
    PPC("PeerCoin"),
    PPP("PayPie"),
    PPT("Populous"),
    PPY("Peerplays"),
    PQT("PAquarium"),
    PRC("ProsperCoin"),
    PRE("Premium"),
    PRES("President Trump"),
    PRFT("Proof Suite Token"),
    PRG("Paragon"),
    PRIME("PrimeChain"),
    PRIX("Privatix"),
    PRL("Oyster Pearl"),
    PRM("PrismChain"),
    PRO("Propy"),
    PROC("ProCurrency"),
    PROD("Darenta"),
    PROPS("Props"),
    PROTON("Proton"),
    PROUD("PROUD Money"),
    PRP("Papyrus"),
    PRPS("Purpose"),
    PRX("Printerium"),
    PSB("PesoBit"),
    PSD("Poseidon"),
    PSEUD("PseudoCash"),
    PSI("PSIcoin"),
    PST("Primas"),
    PSY("Psilocybin"),
    PTA("PentaCoin"),
    PTC("Plutocoin"),
    PTOY("Patientory"),
    PTR("Petro"),
    PTS("Protoshares"),
    PULSE("Pulse"),
    PUPA("PupaCoin"),
    PURA("Pura"),
    PURE("Pure"),
    PURK("Purk"),
    PUSHI("Pushi"),
    PUT("PutinCoin"),
    PWR("PWR Coin"),
    PX("PXcoin"),
    PXC("PhoenixCoin"),
    PXI("Prime-X1"),
    PXL("Phalanx"),
    PYC("PayCoin"),
    PYLNT("Pylon Network"),
    PYN("Paycentos"),
    PYP("PayPro"),
    PYT("Payther"),
    PZM("Prizm"),
    Q1S("Quantum1Net"),
    Q2C("QubitCoin"),
    QASH("Quoine Liquid"),
    QAU("Quantum"),
    QBC("Quebecoin"),
    QBK("QuBuck Coin"),
    QBT("Cubits"),
    QCN("Quazar Coin"),
    QKC("QuarkChain"),
    QLC("QLC Chain"),
    QORA("QoraCoin"),
    QRK("QuarkCoin"),
    QRL("Quantum Resistant Ledger"),
    QSLV("Quicksilver coin"),
    QSP("Quantstamp"),
    QTL("Quatloo"),
    QTUM("QTUM"),
    QTZ("Quartz"),
    QUN("QunQun"),
    QVT("Qvolta"),
    QWARK("Qwark"),
    QWC("Qwertycoin"),
    R("Revain"),
    RAC("RAcoin"),
    RADI("RadicalCoin"),
    RADS("Radium"),
    RAIN("Condensate"),
    RAP("Rapture"),
    RATIO("Ratio"),
    RAVE("Ravelous"),
    RBIES("Rubies"),
    RBIT("ReturnBit"),
    RBR("Ribbit Rewards"),
    RBT("Rimbit"),
    RBTC("Bitcoin Revolution"),
    RBX("RiptoBuX"),
    RBY("RubyCoin"),
    RC("Russiacoin"),
    RCC("Reality Clash"),
    RCN("Ripio"),
    RCT("RealChain"),
    RCX("RedCrowCoin"),
    RDC("Ordocoin"),
    RDD("Reddcoin"),
    RDN("Raiden Network"),
    REA("Realisto"),
    REAL("REAL"),
    REBL("REBL"),
    REC("Regalcoin"),
    RED("Redcoin"),
    REDBUX("redBUX"),
    REDN("Reden"),
    REE("ReeCoin"),
    REF("RefToken"),
    REL("Reliance"),
    REM("REMME"),
    REN("Republic Token"),
    REP("Augur"),
    REPO("Repo Coin"),
    REPUX("Repux"),
    REQ("Request Network"),
    REV("Revenu"),
    REX("Imbrex"),
    RFL("RAFL"),
    RFR("Refereum"),
    RGC("RG Coin"),
    RHEA("Rhea"),
    RHOC("RChain"),
    RIC("Riecoin"),
    RICE("RiceCoin"),
    RIDE("Ride My Car"),
    RING("RingCoin"),
    RIPO("RipOffCoin"),
    RIPT("RiptideCoin"),
    RISE("Rise"),
    RIYA("Etheriya"),
    RKC("Royal Kingdom Coin"),
    RKT("Rock Token"),
    RLC("iEx.ec"),
    RLX("Relex"),
    RMC("Russian Mining Coin"),
    RMS("Resumeo Shares"),
    RMT("SureRemit"),
    RNC("ReturnCoin"),
    RNDR("Render Token"),
    RNS("RenosCoin"),
    RNT("OneRoot Network"),
    RNTB("BitRent"),
    ROCK("RocketCoin "),
    ROE("Rover Coin"),
    ROI("ROIcoin"),
    ROK("Rockchain"),
    ROOT("RootCoin"),
    ROOTS("RootProject"),
    ROS("ROS Coin"),
    ROUND("RoundCoin"),
    ROX("Robotina"),
    ROYAL("RoyalCoin"),
    RPC("RonPaulCoin"),
    RPM("Render Payment"),
    RPX("Red Pulse"),
    RRT("Recovery Right Tokens"),
    RST("REGA Risk Sharing Token"),
    RT2("RotoCoin"),
    RTB("AB-CHAIN"),
    RTE("Rate3 "),
    RUBIT("Rublebit"),
    RUBY("Rubius"),
    RUFF("Ruff"),
    RUP("Rupee"),
    RUPX("Rupaya"),
    RUST("RustCoin"),
    RUSTBITS("Rustbits"),
    RVN("Ravencoin"),
    RVR("Revolution VR"),
    RVT("Rivetz"),
    RYC("RoyalCoin"),
    RYCN("RoyalCoin 2.0"),
    RYO("Ryo"),
    RYZ("Anryze"),
    RZR("RazorCoin"),
    S8C("S88 Coin"),
    SABR("SABR Coin"),
    SAF("Safinus"),
    SAFE("SafeCoin"),
    SAFEX("SafeExchangeCoin"),
    SAGA("SagaCoin"),
    SAK("SharkCoin"),
    SAL("SalPay"),
    SALT("Salt Lending"),
    SAN("Santiment"),
    SAND("BeachCoin"),
    SANDG("Save and Gain"),
    SAR("SARCoin"),
    SAT("Satisfaction Token"),
    SAT2("Saturn2Coin"),
    SBC("StableCoin"),
    SBD("Steem Backed Dollars"),
    SBTC("Super Bitcoin"),
    SC("Siacoin"),
    SCASH("SpaceCash"),
    SCC("StockChain Coin"),
    SCL("Sociall"),
    SCN("Swiscoin"),
    SCOOBY("Scooby coin"),
    SCOR("Scorista"),
    SCORE("Scorecoin"),
    SCOT("Scotcoin"),
    SCR("Scorum"),
    SCRL("Scroll"),
    SCRPT("ScryptCoin"),
    SCRT("SecretCoin"),
    SCT("ScryptToken"),
    SCX("Swachhcoin"),
    SDAO("Solar DAO"),
    SDC("ShadowCash"),
    SDP("SydPakCoin"),
    SDRN("Senderon"),
    SEEDS("SeedShares"),
    SEL("SelenCoin"),
    SEM("Semux"),
    SEN("Sentaro"),
    SENC("Sentinel Chain"),
    SEND("Social Send"),
    SENSE("Sense Token"),
    SENT("Sentinel"),
    SEQ("Sequence"),
    SERA("Seraph"),
    SET("Setcoin"),
    SETH("Sether"),
    SFC("Solarflarecoin"),
    SFE("Safecoin"),
    SFR("SaffronCoin"),
    SFU("Saifu"),
    SGL("Sigil"),
    SGN("Signals Network"),
    SGR("Sugar Exchange"),
    SH("Shilling"),
    SHA("Shacoin"),
    SHADE("ShadeCoin"),
    SHIFT("Shift"),
    SHIP("ShipChain"),
    SHL("Oyster Shell"),
    SHLD("ShieldCoin"),
    SHND("StrongHands"),
    SHORTY("ShortyCoin"),
    SHOW("ShowCoin"),
    SHP("Sharpe Capital"),
    SHPING("Shping Coin"),
    SHR("ShareRing"),
    SHREK("ShrekCoin"),
    SIB("SibCoin"),
    SIC("Swisscoin"),
    SIFT("Smart Investment Fund Token"),
    SIG("Signal"),
    SIGT("Signatum"),
    SIGU("Singular"),
    SILK("SilkCoin"),
    SISA("Strategic Investments in Significant Areas"),
    SJCX("StorjCoin"),
    SKB("Sakura Bloom"),
    SKC("Skeincoin"),
    SKIN("Skincoin"),
    SKM("Skrumble Network"),
    SKR("Sakuracoin"),
    SKRP("Skraps"),
    SKULL("Pirate Blocks"),
    SKY("Skycoin"),
    SLG("SterlingCoin"),
    SLING("Sling Coin"),
    SLM("SlimCoin"),
    SLR("SolarCoin"),
    SLS("SaluS"),
    SLT("SmartLands"),
    SLX("Slate"),
    SMAC("Social Media Coin"),
    SMART("SmartCash"),
    SMC("SmartCoin"),
    SMF("SmurfCoin"),
    SMLY("SmileyCoin"),
    SMNX("SMNX"),
    SMSR("Samsara Coin"),
    SMT("SmartMesh"),
    SNC("SunContract"),
    SND("Sandcoin"),
    SNGLS("SingularDTV"),
    SNIP("SnipCoin"),
    SNK("Sosnovkino"),
    SNM("SONM"),
    SNOV("Snovio"),
    SNRG("Synergy"),
    SNS("Sense"),
    SNT("Status Network Token"),
    SNTR("Silent Notary"),
    SOAR("Soarcoin"),
    SOC("All Sports Coin"),
    SOCC("SocialCoin"),
    SOIL("SoilCoin"),
    SOJ("Sojourn Coin"),
    SOL("Sola"),
    SOLE("SoleCoin"),
    SONG("Song Coin"),
    SOON("SoonCoin"),
    SOUL("SoulCoin"),
    SP("Sex Pistols"),
    SPA("SpainCoin"),
    SPACE("SpaceCoin"),
    SPANK("SpankChain"),
    SPC("SpinCoin"),
    SPD("Stipend"),
    SPEC("SpecCoin"),
    SPEND("Spend"),
    SPF("SportyCo"),
    SPHR("Sphere Coin"),
    SPHTX("SophiaTX"),
    SPICE("SPiCE Venture Capital "),
    SPK("Sparks"),
    SPKTR("Ghost Coin"),
    SPLB("SimpleBank"),
    SPM("Supreme"),
    SPN("Spoon"),
    SPORT("SportsCoin"),
    SPOTS("Spots"),
    SPR("Spreadcoin"),
    SPRTS("Sprouts"),
    SPT("Spots"),
    SPX("Specie"),
    SQL("Squall Coin"),
    SQOIN("StasyQ"),
    SQP("SqPay"),
    SRC("SecureCoin"),
    SRN("SirinLabs"),
    SRNT("Serenity"),
    SRT("Scrypto"),
    SS("Sharder"),
    SSC("SelfSell"),
    SSD("Sonic Screw Driver Coin"),
    SSH("StreamSpace"),
    SSS("ShareChain"),
    SSTC("SunShotCoin"),
    SSV("SSVCoin"),
    STA("Starta"),
    STAC("STAC"),
    STAK("Straks"),
    STALIN("StalinCoin"),
    STAR("StarCoin"),
    START("StartCoin"),
    STAX("Staxcoin"),
    STC("StarChain"),
    STCN("Stakecoin"),
    STEEM("Steem"),
    STEPS("Steps"),
    STEX("STEX"),
    STHR("Stakerush"),
    STK("STK Token"),
    STN("Steneum Coin"),
    STO("Save The Ocean"),
    STOCKBET("StockBet"),
    STORJ("Storj"),
    STORM("Storm"),
    STP("StashPay"),
    STQ("Storiqa Token"),
    STR("StarCoin"),
    STRAT("Stratis"),
    STS("STRESScoin"),
    STT("Staramba"),
    STU("BitJob"),
    STV("Sativa Coin"),
    STX("Stox"),
    SUB("Substratum Network"),
    SUCR("Sucre"),
    SUMO("Sumokoin"),
    SUP("Supcoin"),
    SUPER("SuperCoin"),
    SUR("Suretly"),
    SVD("Savedroid"),
    SWARM("SwarmCoin"),
    SWC("Scanetchain Token"),
    SWEET("SweetStake"),
    SWFTC("SwftCoin"),
    SWIFT("BitSwift"),
    SWING("SwingCoin"),
    SWM("Swarm Fund"),
    SWT("Swarm City Token"),
    SWTH("Switcheo"),
    SXC("SexCoin"),
    SXDT("SPECTRE Dividend Token"),
    SXUT("SPECTRE Utility Token"),
    SYC("SynchroCoin"),
    SYNC("SyncCoin"),
    SYNX("Syndicate"),
    SYS("SysCoin"),
    TAAS("Token as a Service"),
    TAB("MollyCoin"),
    TAG("TagCoin"),
    TAGR("Think And Get Rich Coin"),
    TAJ("TajCoin"),
    TAK("TakCoin"),
    TAM("TamaGucci"),
    TAP("TappingCoin"),
    TAT("Tatiana Coin"),
    TAU("Lamden Tau"),
    TBAR("Titanium BAR"),
    TBCX("TrashBurn"),
    TBT("T-BOT"),
    TBX("Tokenbox"),
    TCR("Thecreed"),
    TCT("TokenClub "),
    TDFB("TDFB"),
    TDP("TrueDeck"),
    TDS("TokenDesk"),
    TDX("Tidex Token"),
    TDZ("Tradelize"),
    TEAM("TeamUP"),
    TEC("TeCoin"),
    TECH("TechCoin"),
    TEK("TekCoin"),
    TEL("Telcoin"),
    TELL("Tellurion"),
    TEN("Tokenomy"),
    TENNET("Tennet"),
    TER("TerraNovaCoin"),
    TERN("Ternio"),
    TES("TeslaCoin"),
    TESLA("TeslaCoilCoin"),
    TFC("The Freedom Coin"),
    TFD("TE-FOOD"),
    TFL("True Flip Lottery"),
    TGAME("TrueGame"),
    TGC("TigerCoin"),
    TGT("TargetCoin"),
    THC("The Hempcoin"),
    THETA("Theta"),
    THNX("ThankYou"),
    THRT("ThriveToken"),
    THS("TechShares"),
    TIA("Tianhe"),
    TIC("TrueInvestmentCoin"),
    TIE("Ties Network"),
    TIG("Tigereum"),
    TIME("Time"),
    TIO("Trade.io"),
    TIP("Tip Blockchain"),
    TIPS("FedoraCoin"),
    TIT("TitCoin"),
    TIX("Blocktix"),
    TKA("Tokia"),
    TKLN("Taklimakan"),
    TKN("TokenCard"),
    TKR("CryptoInsight"),
    TKS("Tokes"),
    TKT("Crypto Tickets"),
    TKY("THEKEY Token"),
    TLP("TulipCoin"),
    TMC("TimesCoin"),
    TME("Timereum"),
    TMT("ToTheMoon"),
    TNB("Time New Bank"),
    TNC("Trinity Network Credit"),
    TNT("Tierion"),
    TOA("TOA Coin"),
    TODAY("TodayCoin"),
    TOK("TokugawaCoin"),
    TOKC("Tokyo Coin"),
    TOM("Tomahawkcoin"),
    TOMO("TomoChain"),
    TOR("TorCoin"),
    TOT("TotCoin"),
    TPAY("TokenPay"),
    TPC("TPCash"),
    TPG("Troll Payment"),
    TRA("Tetra"),
    TRAC("OriginTrail"),
    TRAK("TrakInvest"),
    TRC("TerraCoin"),
    TRCK("Truckcoin"),
    TRCT("Tracto"),
    TRDT("Trident"),
    TRF("Travelflex"),
    TRI("Triangles Coin"),
    TRIA("Triaconta"),
    TRIBE("TribeToken"),
    TRICK("TrickyCoin"),
    TRIG("Trigger"),
    TRIP("Trippki"),
    TRK("TruckCoin"),
    TRN("Ternion"),
    TROLL("Trollcoin"),
    TRON("Positron"),
    TRST("TrustCoin"),
    TRTL("TurtleCoin"),
    TRUMP("TrumpCoin"),
    TRUST("TrustPlus"),
    TRV("Travel Coin"),
    TRVC("Trivecoin"),
    TRW("Triwer"),
    TRX("Tronix"),
    TSC("ThunderStake"),
    TSE("TattooCoin"),
    TSL("Energo"),
    TT("TravelChain"),
    TTC("TittieCoin"),
    TTT("Tap Project"),
    TUBE("BitTube"),
    TUR("Turron"),
    TUSD("True USD"),
    TUT("Tutellus"),
    TWIST("TwisterCoin"),
    TWLV("Twelve Coin"),
    TX("Transfer"),
    TZC("TrezarCoin"),
    U("Ucoin"),
    U42("You42"),
    UAEC("United Arab Emirates Coin"),
    UBC("Ubcoin"),
    UBEX("Ubex"),
    UBIQ("Ubiqoin"),
    UBQ("Ubiq"),
    UBT("UniBright"),
    UBTC("UnitedBitcoin"),
    UCASH("U.CASH"),
    UCN("UC Coin"),
    UCT("UCOT"),
    UET("Useless Ethereum Token"),
    UETL("Useless Eth Token Lite"),
    UFO("UFO Coin"),
    UFR("Upfiring"),
    UGC("ugChain"),
    UIS("Unitus"),
    UKG("UnikoinGold"),
    ULTC("Umbrella"),
    UMC("Umbrella Coin"),
    UNAT("Unattanium"),
    UNB("UnbreakableCoin"),
    UNC("UnCoin"),
    UNF("Unfed Coin"),
    UNI("Universe"),
    UNIFY("Unify"),
    UNIQ("Uniqredit"),
    UNIT("Universal Currency"),
    UNITS("GameUnits"),
    UNITY("SuperNET"),
    UNO("Unobtanium"),
    UNRC("UniversalRoyalCoin"),
    UP("UpToken"),
    UPP("Sentinel Protocol"),
    UQC("Uquid Coin"),
    UR("UR"),
    URALS("Urals Coin"),
    URO("UroCoin"),
    USC("Ultimate Secure Cash"),
    USDC("USCoin"),
    USDE("UnitaryStatus Dollar"),
    USDT("Tether"),
    USOAMIC("USOAMIC"),
    USX("Unified Society USDEX"),
    UTC("UltraCoin"),
    UTH("Uther"),
    UTIL("Utility Coin"),
    UTK("Utrust"),
    UTN("Universa"),
    UTNP("Universa Token"),
    UTT("United Traders Token"),
    UUU("U Network"),
    UWC("Uwezocoin"),
    VAL("Valorbit"),
    VANY("Vanywhere"),
    VAPOR("Vaporcoin"),
    VDO("VidioCoin"),
    VEC2("VectorCoin 2.0 "),
    VEE("BLOCKv"),
    VEG("BitVegan"),
    VEGA("VEGA"),
    VEN("Vechain"),
    VERI("Veritaseum"),
    VERSA("Versa Token"),
    VIA("ViaCoin"),
    VIB("Viberate"),
    VIBE("VIBEHub"),
    VIC("Victorium"),
    VID("VideoCoin"),
    VIDT("V-ID"),
    VIDZ("PureVidz"),
    VIEW("Viewly"),
    VIG("TheVig"),
    VIN("VinChain"),
    VIOR("ViorCoin"),
    VIP("VIP Tokens"),
    VIRAL("Viral Coin"),
    VISIO("Visio"),
    VIT("Vice Industry Token"),
    VITAE("Vitae"),
    VITE("VITE"),
    VIU("Viuly"),
    VIVO("VIVO Coin"),
    VLD("Valid"),
    VLR("Valorem"),
    VLT("Veltor"),
    VLTC("VaultCoin"),
    VLUX("VLUX"),
    VLX("Velox"),
    VMC("VirtualMining Coin"),
    VME("VeriME"),
    VNT("Veredictum"),
    VOISE("Voise"),
    VOLT("BitVolt"),
    VOOT("VootCoin"),
    VOT("Votecoin"),
    VOYA("Voyacoin"),
    VPRC("VapersCoin"),
    VRA("Verasity"),
    VRC("VeriCoin"),
    VRM("Verium"),
    VRP("Prosense.tv"),
    VRS("Veros"),
    VSL("vSlice"),
    VST("Vestarin"),
    VSX("Vsync"),
    VTA("VirtaCoin"),
    VTC("Vertcoin"),
    VTN("Voltroon"),
    VTR("Vtorrent"),
    VTX("Vertex"),
    VTY("Victoriouscoin"),
    VUC("Virta Unique Coin"),
    VULC("Vulcano"),
    VVI("VV Coin"),
    VZT("Vezt"),
    W3C("W3Coin"),
    WAB("WABnetwork"),
    WABI("WaBi"),
    WAGE("Digiwage"),
    WAN("Wanchain"),
    WAND("WandX"),
    WARP("WarpCoin"),
    WASH("WashingtonCoin"),
    WAVES("Waves"),
    WAX("Worldwide Asset eXchange"),
    WAY("WayCoin"),
    WBB("Wild Beast Coin"),
    WBTC("WorldBTC"),
    WC("WhiteCoin"),
    WCG("World Crypto Gold"),
    WCT("Waves Community Token"),
    WDC("WorldCoin"),
    WEALTH("WealthCoin"),
    WEB("Webchain"),
    WELL("Well"),
    WEX("Wexcoin"),
    WGC("World Gold Coin"),
    WGO("WavesGO"),
    WGR("Wagerr"),
    WHL("WhaleCoin"),
    WIC("Wi Coin"),
    WIIX("Wiix"),
    WILD("Wild Crypto"),
    WIN("WCoin"),
    WINE("WineCoin"),
    WINGS("Wings DAO"),
    WINK("Wink"),
    WINS("WinStars"),
    WISC("WisdomCoin"),
    WISH("WishFinance"),
    WIZ("Crowdwiz"),
    WLK("Wolk"),
    WMC("WMCoin"),
    WNET("Wavesnode.net"),
    WOLF("Insanity Coin"),
    WOMEN("WomenCoin"),
    WOP("WorldPay"),
    WORM("HealthyWorm"),
    WPR("WePower"),
    WRC("WarCoin"),
    WRT("WRTcoin"),
    WSC("WiserCoin"),
    WSH("Wish Finance"),
    WSX("WeAreSatoshi"),
    WT("WeToken"),
    WTC("Waltonchain"),
    WTT("Giga Watt"),
    WYR("Wyrify"),
    WYS("Wysker"),
    X2("X2Coin"),
    X8X("X8Currency"),
    XAI("AICoin"),
    XAS("Asch"),
    XAU("XauCoin"),
    XAUR("Xaurum"),
    XBC("BitcoinPlus"),
    XBI("Bitcoin Incognito"),
    XBL("Billionaire Token"),
    XBOT("SocialXbotCoin"),
    XBP("Black Pearl Coin"),
    XBS("Bitstake"),
    XBTS("Beats"),
    XBTY("Bounty"),
    XBY("XtraBYtes"),
    XC("X11 Coin"),
    XCASH("Xcash"),
    XCD("Capdax"),
    XCE("Cerium"),
    XCEL("XcelTrip"),
    XCI("Cannabis Industry Coin"),
    XCJ("CoinJob"),
    XCLR("ClearCoin"),
    XCM("CoinMetro"),
    XCN("Cryptonite"),
    XCO("XCoin"),
    XCP("CounterParty"),
    XCPO("Copico"),
    XCR("Crypti"),
    XCRE("Creatio"),
    XCS("CybCSec Coin"),
    XCT("C-Bits"),
    XCXT("CoinonatX"),
    XDB("DragonSphere"),
    XDCE("XinFin Coin"),
    XDE2("XDE II"),
    XDN("DigitalNote "),
    XDNA("XDNA"),
    XDP("DogeParty"),
    XDQ("Dirac Coin"),
    XEC("Eternal Coin"),
    XEL("Elastic"),
    XEM("NEM"),
    XEN("XenixCoin"),
    XES("Proxeus"),
    XET("Eternal Token"),
    XFC("Forever Coin"),
    XFT("Fantasy Cash"),
    XG("XG Sports"),
    XGB("GoldenBird"),
    XGOX("Go!"),
    XGR("GoldReserve"),
    XGS("GenesisX"),
    XHI("HiCoin"),
    XHV("Haven Protocol"),
    XID("International Diamond Coin"),
    XIOS("Xios"),
    XJO("JouleCoin"),
    XLB("LibertyCoin"),
    XLC("LeviarCoin"),
    XLM("Stellar"),
    XLR("Solaris"),
    XMC("Monero Classic"),
    XMCC("Monoeci"),
    XMG("Coin Magi"),
    XMN("Motion"),
    XMO("Monero Original"),
    XMR("Monero"),
    XMRG("Monero Gold"),
    XMS("Megastake"),
    XMV("MoneroV"),
    XMX("XMax"),
    XMY("MyriadCoin"),
    XNA("DeOxyRibose"),
    XNC("XenCoin"),
    XNG("Enigma"),
    XNK("Ink Protocol"),
    XNN("Xenon"),
    XNX("XanaxCoin"),
    XP("Experience Points"),
    XPAT("Bitnation Pangea"),
    XPB("Pebble Coin"),
    XPD("PetroDollar"),
    XPH("PharmaCoin"),
    XPM("PrimeCoin"),
    XPO("Opair"),
    XPOKE("PokeChain"),
    XPRO("ProCoin"),
    XPS("PoisonIvyCoin"),
    XPST("PokerSports"),
    XPTX("PlatinumBAR"),
    XPY("PayCoin"),
    XQN("Quotient"),
    XRA("Ratecoin"),
    XRE("RevolverCoin"),
    XRED("X Real Estate Development"),
    XRL("Rialto.AI"),
    XRP("XRP"),
    XSB("Extreme Sportsbook"),
    XSEED("BitSeeds"),
    XSG("Snowgem"),
    XSH("SHIELD"),
    XSI("Stability Shares"),
    XSN("Stakenet"),
    XSP("PoolStamp"),
    XSPEC("Spectre"),
    XST("StealthCoin"),
    XSTC("Safe Trade Coin"),
    XT("ExtremeCoin"),
    XT3("Xt3ch"),
    XTC("TileCoin"),
    XTL("Stellite"),
    XTO("Tao"),
    XTRA("ExtraCredit"),
    XTROPTIONS("TROPTIONS"),
    XTZ("Tezos"),
    XUC("Exchange Union"),
    XUEZ("XUEZ"),
    XUN("UltraNote"),
    XUP("UPcoin"),
    XVC("Vcash"),
    XVE("The Vegan Initiative"),
    XVG("Verge"),
    XVP("VirtacoinPlus"),
    XWC("WhiteCoin"),
    XWT("World Trade Funds"),
    XXX("XXXCoin"),
    XYO("XY Oracle"),
    XZC("ZCoin"),
    YAC("YAcCoin"),
    YAY("YAYcoin"),
    YBC("YbCoin"),
    YCE("MYCE"),
    YEE("Yee"),
    YES("YesCoin"),
    YMC("YamahaCoin"),
    YOC("YoCoin"),
    YOVI("YobitVirtualCoin"),
    YOYOW("Yoyow"),
    YUM("Yumerium"),
    YUP("Crowdholding"),
    Z2("Z2 Coin"),
    Z8BIT("8BIT Coin"),
    Z8BT("8 Circuit Studios"),
    ZAB("ZABERcoin"),
    ZAP("Zap"),
    ZBC("Zilbercoin"),
    ZCC("ZCC Coin"),
    ZCG("ZCashGOLD"),
    ZCL("ZClassic"),
    ZCN("0chain"),
    ZCO("Zebi Coin"),
    ZEC("ZCash"),
    ZECD("ZCashDarkCoin"),
    ZED("ZedCoins"),
    ZEIT("ZeitCoin"),
    ZEL("Zelcash"),
    ZEN("ZenCash"),
    ZENI("Zennies"),
    ZEPH("Project Zephyr"),
    ZER("Zero"),
    ZET("ZetaCoin"),
    ZET2("Zeta2Coin"),
    ZIL("Zilliqa"),
    ZINC("ZINC"),
    ZIPT("Zippie"),
    ZIX("ZIX Token"),
    ZLQ("ZLiteQubit"),
    ZMN("ZMINE"),
    ZMR("Monero 0"),
    ZNA("Zenome"),
    ZNE("ZoneCoin"),
    ZNT("OpenZen"),
    ZNY("BitZeny"),
    ZOI("Zoin"),
    ZOOM("ZoomCoin"),
    ZPT("Zeepin"),
    ZRC("ZiftrCoin"),
    ZRX("0x"),
    ZSC("ZeroState"),
    ZSE("ZSEcoin"),
    ZUP("Zupply Token"),
    ZUR("Zurcoin"),
    ZXC("Oxcert"),
    ZXT("Zcrypt"),
    ZYD("ZayedCoin"),
    ZZZOUND("Inmusik"),
    ZZZ007("007 coin"),
    ZZZ1337("1337"),
    ZZZ1CR("1Credit"),
    ZZZ1ST("FirstBlood"),
    ZZZ2015("2015 coin"),
    ZZZ2BACCO("2BACCO Coin"),
    ZZZ2GIVE("2GiveCoin"),
    ZZZ300("300 token"),
    ZZZ32BIT("32Bitcoin"),
    ZZZ365("365Coin"),
    ZZZ3DES("3DES"),
    ZZZ404("404Coin"),
    ZZZ42("42 Coin"),
    ZZZ611("SixEleven"),
    ZZZ808("808"),
    ZZZ888("Octocoin"),
    EUR("Euro"),
    GBP("Pound Sterling"),
    JPY("Japanese Yen"),
    RUB("Russian Ruble"),
    USD("US Dollar"),
}
